/**
 * JavaScriptチートシートのデータ。
 *
 * 表示側（components）はこの構造だけを見るので、ここに書いた順序がそのまま
 * 目次とページの並び順になる。項目は必ず helpers.ts の item() で生成する。
 *
 *   item(id, label, syntax, description, note?, status?, keywords?)
 *
 * - id はシート内で一意。目次のアンカー（#id）とReactのkeyに使われる
 * - status は normal / info / warning / danger。省略時は normal
 * - XSS などセキュリティ事故につながる書き方には danger、元の配列を書き換えるなど
 *   気付きにくい落とし穴には warning、推奨の書き方には info を付ける。
 *   バッジの色が唯一の警告表示になるため、付け忘れると危険が伝わらない
 * - 言語は ES2015 以降の書き方が前提。比較的新しい機能は、使えるようになった時期を note に書く
 * - 出典は MDN。対応状況（Baseline）が変わりうる記述は MDN で確認してから直す（2026-09-16確認）
 * - keywords は検索用の別名。全角/半角・大文字小文字は normalizeSearch が吸収する
 * - 内容を直したら updatedAt も更新する
 */
import { item } from "../helpers";
import type { CheatSheet } from "../types";

export const javascriptCheatSheet: CheatSheet = {
  id: "javascript-reference",
  slug: "javascript",
  title: "JavaScript チートシート",
  name: "JavaScript",
  description:
    "変数・関数・配列から非同期処理、モジュール、DOM操作、fetch までをまとめたJavaScriptリファレンス。",
  eyebrow: "Programming language",
  accent: "#b58900",
  keywords: ["javascript", "js", "ecmascript", "es6", "dom", "非同期", "fetch"],
  updatedAt: "2026-09-16",
  sources: [
    {
      label: "MDN JavaScript リファレンス",
      url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference",
    },
    { label: "MDN Web API", url: "https://developer.mozilla.org/ja/docs/Web/API" },
  ],
  sections: [
    // 宣言のしかたと型。const を基本にする方針を最初に示す。
    {
      id: "variables",
      title: "変数・データ型",
      description: "再代入しない値は const、する値は let。ES2015 以降の書き方が前提。",
      items: [
        item(
          "const",
          "再代入しない変数",
          "const taxRate = 0.1;",
          "再代入できない変数を宣言する。基本はこれを使う。",
          "オブジェクトや配列の中身は変更できる。",
          "info",
        ),
        item(
          "let",
          "再代入する変数",
          "let count = 0;",
          "再代入できる変数を宣言する。ブロック {} の中だけで有効。",
        ),
        item(
          "var",
          "古い変数宣言",
          "var total = 0;",
          "関数単位で有効になり、宣言が先頭へ巻き上げられる。",
          "新しいコードでは let / const を使う。",
          "warning",
        ),
        item(
          "typeof",
          "型を調べる",
          "typeof value",
          '型名を "string" や "number" などの文字列で返す。',
          'typeof null は "object" になる。配列かどうかは Array.isArray() で判定する。',
        ),
        item(
          "primitive-types",
          "プリミティブ型",
          "string / number / bigint / boolean / undefined / symbol / null",
          "オブジェクト以外の7種類の値。",
          "値そのものは変更できず、代入するとコピーされる。",
        ),
        item(
          "template-literal",
          "テンプレートリテラル",
          "`合計: ${price * qty}円`",
          "バッククォートで囲み、${} に式を埋め込む。",
          "改行もそのまま書ける。",
        ),
        item(
          "null-undefined",
          "null と undefined",
          "let selected = null;",
          "「値がない」ことを明示するときは null を代入する。",
          "未代入の変数や存在しないプロパティは undefined になる。",
        ),
        item(
          "bigint",
          "大きな整数",
          "const big = 9007199254740993n;",
          "末尾に n を付けると BigInt になり、大きな整数を正確に扱える。",
          "Number と混ぜて計算すると TypeError になる。",
        ),
      ],
    },
    // 比較と、値が無いときの扱い。== と || の落とし穴を ===・?? の隣に置く。
    {
      id: "operators",
      title: "演算子・比較",
      description: "比較は === が基本。値が無いときの扱いは ?? と ?. で書く。",
      items: [
        item(
          "strict-equal",
          "厳密等価",
          "a === b",
          "型も含めて等しいかを比較する。",
          "否定は !==。",
          "info",
        ),
        item(
          "loose-equal",
          "等価（型変換あり）",
          "a == b",
          "型を変換してから比較する。",
          '0 == "" が true になるなど直感に反する。null / undefined の判定以外では使わない。',
          "warning",
        ),
        item(
          "nullish-coalescing",
          "null / undefined のときの既定値",
          'const name = input ?? "ゲスト";',
          "左辺が null か undefined のときだけ右辺を使う。",
          '0 や "" はそのまま残る。',
          "info",
        ),
        item(
          "logical-or-default",
          "falsy のときの既定値",
          "const limit = input || 10;",
          "左辺が falsy なら右辺を使う。",
          '0 や "" も置き換わるので、数値の既定値には ?? を使う。',
        ),
        item(
          "optional-chaining",
          "オプショナルチェーン",
          "user?.profile?.name",
          "途中が null / undefined なら、エラーにせず undefined を返す。",
        ),
        item(
          "optional-call",
          "あるときだけ呼び出す",
          "onChange?.(value)",
          "関数が定義されているときだけ呼び出す。",
        ),
        item(
          "logical-assignment",
          "未設定なら代入",
          "options.retry ??= 3;",
          "左辺が null / undefined のときだけ代入する。",
          "||= は falsy のとき、&&= は truthy のときに代入する。",
        ),
        item(
          "ternary",
          "条件で値を切り替える",
          'const label = isAdmin ? "管理者" : "一般";',
          "条件が truthy なら前、そうでなければ後ろの値になる。",
          "入れ子にすると読みにくいので if に分ける。",
        ),
        item(
          "spread",
          "スプレッド構文",
          "const merged = [...a, ...b];",
          "配列やオブジェクトの中身を展開する。",
          "{ ...base, ...override } のように後ろの値が優先される。",
        ),
        item(
          "falsy-values",
          "falsy な値",
          'false / 0 / -0 / 0n / "" / null / undefined / NaN',
          "条件式で偽として扱われる値の一覧。これ以外はすべて truthy。",
          '"0" や [] や {} は truthy。',
        ),
      ],
    },
    // 分岐と繰り返し。for...in は配列に使わないよう、for...of と Object.entries() を並べる。
    {
      id: "control",
      title: "条件分岐・ループ",
      description: "配列は for...of、オブジェクトは Object.entries() と組み合わせて回す。",
      items: [
        item(
          "if-else",
          "条件分岐",
          "if (score >= 80) { … } else if (score >= 60) { … } else { … }",
          "条件ごとに処理を分ける。",
        ),
        item(
          "switch",
          "値ごとの分岐",
          'switch (status) { case "done": … break; default: … }',
          "値に一致した case から処理を始める。",
          "break を書き忘れると、次の case まで続けて実行される。",
        ),
        item(
          "for",
          "回数を決めたループ",
          "for (let i = 0; i < items.length; i++) { … }",
          "カウンター変数を使って繰り返す。",
        ),
        item(
          "for-of",
          "要素を順に取り出す",
          "for (const item of items) { … }",
          "配列・文字列・Map・Set などの値を順に取り出す。",
          "break / continue が使える。",
          "info",
        ),
        item(
          "for-in",
          "キーを列挙する",
          "for (const key in obj) { … }",
          "オブジェクトの列挙可能なキーを回す。",
          "継承したプロパティも対象になる。配列には使わない。",
          "warning",
        ),
        item(
          "entries-loop",
          "インデックス付きで回す",
          "for (const [index, item] of items.entries()) { … }",
          "インデックスと要素を同時に取り出す。",
        ),
        item(
          "object-loop",
          "オブジェクトのキーと値を回す",
          "for (const [key, value] of Object.entries(obj)) { … }",
          "自身のプロパティだけを、キーと値の組で回す。",
        ),
        item(
          "while",
          "条件が続くあいだ繰り返す",
          "while (queue.length > 0) { … }",
          "条件が truthy のあいだ繰り返す。",
          "少なくとも1回実行するなら do { … } while (条件);",
        ),
        item(
          "break-continue",
          "ループを抜ける／次へ進む",
          "break; / continue;",
          "break はループを終了し、continue は次の周回へ進む。",
        ),
      ],
    },
    // 関数の書き方。アロー関数と this の関係を注記に残す。
    {
      id: "functions",
      title: "関数",
      description: "短い処理はアロー関数、this を使うメソッドは通常の関数で書く。",
      items: [
        item(
          "function-declaration",
          "関数宣言",
          "function add(a, b) { return a + b; }",
          "名前付きの関数を定義する。",
          "巻き上げられるので、定義より前の行から呼べる。",
        ),
        item(
          "arrow-function",
          "アロー関数",
          "const add = (a, b) => a + b;",
          "短く書ける関数。本体が式1つなら return を省略できる。",
          "自分の this / arguments を持たず、外側のものを使う。",
        ),
        item(
          "arrow-object",
          "オブジェクトを返すアロー関数",
          "const toUser = (name) => ({ name });",
          "返すオブジェクトを丸括弧で囲む。",
          "囲まないと {} が関数の本体として解釈される。",
        ),
        item(
          "default-params",
          "デフォルト引数",
          'function greet(name = "ゲスト") { … }',
          "引数が undefined のときに使う既定値を指定する。",
          "null を渡したときは既定値にならない。",
        ),
        item(
          "rest-params",
          "残余引数",
          "function sum(...nums) { … }",
          "残りの引数をまとめて配列で受け取る。",
        ),
        item(
          "destructured-params",
          "引数の分割代入",
          "function draw({ x, y = 0 }) { … }",
          "オブジェクトで受け取った引数から、必要なプロパティを取り出す。",
          "引数の順番を気にせず、省略もしやすい。",
        ),
        item(
          "closure",
          "クロージャ",
          "const createCounter = () => { let n = 0; return () => ++n; };",
          "外側の変数を覚えたままの関数を返す。",
          "返した関数を呼ぶたびに、保持された n が増えていく。",
        ),
        item(
          "bind",
          "this を固定する",
          "const handler = obj.method.bind(obj);",
          "this を固定した新しい関数を作る。",
          "メソッドをそのままコールバックに渡すと this が外れる。",
        ),
      ],
    },
    // オブジェクトの組み立てとコピー。浅いコピーと深いコピーの違いが要点。
    {
      id: "objects",
      title: "オブジェクト",
      description: "コピーはスプレッド構文（浅い）と structuredClone（深い）を使い分ける。",
      items: [
        item(
          "object-shorthand",
          "省略記法",
          "const user = { name, age, greet() { … } };",
          "同名の変数をそのままプロパティにし、メソッドを短く書く。",
        ),
        item(
          "computed-key",
          "計算プロパティ名",
          "const patch = { [field]: value };",
          "変数や式の値をキー名にする。",
        ),
        item(
          "object-destructuring",
          "分割代入",
          "const { name, age = 20, ...rest } = user;",
          "プロパティを変数に取り出す。既定値や残りの取り出しもできる。",
          "{ name: userName } と書くと別名で取り出せる。",
        ),
        item(
          "array-destructuring",
          "配列の分割代入",
          "const [first, , third] = items;",
          "配列の要素を位置で取り出す。",
          "[a, b] = [b, a] で値を入れ替えられる。",
        ),
        item(
          "spread-copy",
          "コピーして一部を変更",
          "const updated = { ...user, age: 21 };",
          "浅いコピーを作り、指定したプロパティだけ上書きする。",
          "入れ子のオブジェクトは元と共有される。",
        ),
        item(
          "structured-clone",
          "深いコピー",
          "const copy = structuredClone(data);",
          "入れ子のオブジェクトまで丸ごとコピーする。",
          "関数や DOM 要素を含む値はコピーできない。",
          "info",
        ),
        item(
          "object-entries",
          "キーと値の配列にする",
          "Object.entries(obj)",
          "[キー, 値] の配列を返す。",
          "キーだけなら Object.keys()、値だけなら Object.values()。",
        ),
        item(
          "object-from-entries",
          "配列からオブジェクトを作る",
          "Object.fromEntries(entries)",
          "[キー, 値] の配列や Map からオブジェクトを作る。",
          "Object.entries() と組み合わせると、値を変換したオブジェクトを作れる。",
        ),
        item(
          "object-has-own",
          "自身のプロパティか判定",
          'Object.hasOwn(obj, "key")',
          "継承したものを除き、自身がそのプロパティを持つか判定する。",
          "in 演算子は継承したプロパティでも true になる。",
          "info",
        ),
        item(
          "object-freeze",
          "変更できなくする",
          "Object.freeze(config);",
          "プロパティの追加・変更・削除をできなくする。",
          "凍結されるのは1階層目だけ。",
        ),
        item(
          "object-group-by",
          "グループ分け",
          "Object.groupBy(items, (item) => item.category)",
          "関数が返したキーごとに、要素を配列へまとめる。",
          "2024年3月以降の主要ブラウザで使える。",
        ),
      ],
    },
    // 配列メソッド。新しい配列を返すものと、元の配列を書き換えるもの（warning）を区別する。
    {
      id: "arrays",
      title: "配列",
      description:
        "map・filter などは新しい配列を返す。sort・splice・push は元の配列を書き換える。",
      items: [
        item(
          "map",
          "要素を変換",
          "items.map((item) => item.price)",
          "各要素を変換した新しい配列を返す。",
          undefined,
          "info",
        ),
        item(
          "filter",
          "条件で絞り込む",
          "items.filter((item) => item.active)",
          "条件を満たす要素だけの新しい配列を返す。",
        ),
        item(
          "reduce",
          "1つの値に集計",
          "items.reduce((sum, item) => sum + item.price, 0)",
          "要素を順に畳み込み、合計などを求める。",
          "初期値を渡さないと、空配列のとき TypeError になる。",
        ),
        item(
          "find",
          "最初の1件を探す",
          "items.find((item) => item.id === id)",
          "条件を満たす最初の要素を返す。",
          "見つからなければ undefined。位置が欲しいときは findIndex()（無ければ -1）。",
        ),
        item(
          "some-every",
          "条件を満たすか判定",
          "items.some(isValid) / items.every(isValid)",
          "some は1つでも、every はすべてが条件を満たせば true を返す。",
        ),
        item(
          "includes",
          "含まれるか判定",
          "items.includes(value)",
          "指定した値が含まれていれば true を返す。",
          "indexOf() と違い、NaN も見つけられる。",
        ),
        item("at", "末尾から取り出す", "items.at(-1)", "負の数で、末尾から数えた要素を取り出す。"),
        item(
          "for-each",
          "要素ごとに処理",
          "items.forEach((item) => console.log(item))",
          "各要素に対して関数を実行する。戻り値はない。",
          "途中で止められず、async 関数を渡しても完了を待たない。",
        ),
        item(
          "sort",
          "並べ替え（元を変更）",
          "items.sort((a, b) => a - b)",
          "元の配列そのものを並べ替える。",
          "比較関数を省くと文字列として比べるため、10 が 9 より前になる。",
          "warning",
        ),
        item(
          "to-sorted",
          "並べ替えたコピーを返す",
          "items.toSorted((a, b) => a - b)",
          "元の配列を変えずに、並べ替えた新しい配列を返す。",
          "逆順は toReversed()。2023年以降の主要ブラウザで使える。",
          "info",
        ),
        item(
          "slice",
          "一部をコピー",
          "items.slice(1, 3)",
          "開始位置から終了位置の手前までを、新しい配列で返す。",
          "元の配列は変わらない。",
        ),
        item(
          "splice",
          "要素の削除・挿入（元を変更）",
          "items.splice(index, 1)",
          "指定した位置から要素を削除し、必要なら挿入する。",
          "元の配列が変わる。変えたくないときは toSpliced() や filter() を使う。",
          "warning",
        ),
        item(
          "push-pop",
          "末尾に追加／取り出す",
          "items.push(value) / items.pop()",
          "末尾に要素を追加する／末尾の要素を取り出す。",
          "元の配列が変わる。先頭側は unshift() / shift()。",
        ),
        item(
          "flat-map",
          "入れ子を平らにする",
          "nested.flat() / items.flatMap((item) => item.tags)",
          "入れ子の配列を1階層平らにする。flatMap は変換と平坦化を一度に行う。",
        ),
        item(
          "array-from",
          "配列を作る",
          "Array.from({ length: 5 }, (_, i) => i + 1)",
          "長さや反復可能な値から配列を作る。",
          "NodeList を配列に変換するときにも使う。",
        ),
        item(
          "join",
          "文字列に連結",
          'items.join(", ")',
          "要素を区切り文字でつないだ文字列を返す。",
        ),
      ],
    },
    // キーに任意の値を使える辞書（Map）と、重複しない集合（Set）。
    {
      id: "map-set",
      title: "Map・Set",
      description: "任意の値をキーにする辞書は Map、重複しない値の集まりは Set。",
      items: [
        item(
          "map-create",
          "Map を作る",
          "const cache = new Map();\ncache.set(key, value);\ncache.get(key);",
          "任意の値をキーにできる辞書を作る。",
          "オブジェクトと違い、数値やオブジェクトのキーが文字列に変換されない。",
        ),
        item(
          "map-iterate",
          "Map を回す",
          "for (const [key, value] of cache) { … }",
          "キーと値の組を、追加した順に取り出す。",
          "Object.fromEntries(cache) で通常のオブジェクトに変換できる。",
        ),
        item(
          "set-create",
          "Set を作る",
          'const tags = new Set(["js", "css"]);',
          "重複しない値の集まりを作る。",
          "add() で追加しても、同じ値は1つしか入らない。",
        ),
        item(
          "dedupe",
          "配列の重複を除く",
          "[...new Set(items)]",
          "Set を経由して、重複を取り除いた配列を作る。",
          undefined,
          "info",
        ),
        item(
          "has-delete-size",
          "存在確認・削除・件数",
          "set.has(value) / set.delete(value) / set.size",
          "Map と Set に共通する基本操作。",
          "Map の has() / delete() にはキーを渡す。",
        ),
      ],
    },
    // 文字列は変更できないので、どのメソッドも新しい文字列を返す。
    {
      id: "strings",
      title: "文字列・正規表現",
      description: "文字列は変更できないので、メソッドは新しい文字列を返す。",
      items: [
        item(
          "string-includes",
          "含まれるか判定",
          'text.includes("error")',
          "部分文字列が含まれていれば true を返す。",
          "先頭・末尾の判定は startsWith() / endsWith()。",
        ),
        item(
          "string-slice",
          "一部を取り出す",
          "text.slice(0, 10)",
          "開始位置から終了位置の手前までを取り出す。",
          "負の数で末尾から数えられる。",
        ),
        item("split", "区切って配列にする", 'csv.split(",")', "区切り文字で分割した配列を返す。"),
        item(
          "replace-all",
          "すべて置換",
          'text.replaceAll("old", "new")',
          "一致した箇所をすべて置き換える。",
          "replace() は最初の1か所だけ。正規表現を渡すときは g フラグが必要。",
        ),
        item(
          "trim",
          "前後の空白を除く",
          "input.trim()",
          "前後の空白や改行を取り除く。",
          "片側だけなら trimStart() / trimEnd()。",
        ),
        item(
          "pad-start",
          "桁をそろえる",
          'String(month).padStart(2, "0")',
          "指定した長さになるまで先頭を埋める。",
          '"3" が "03" になる。',
        ),
        item(
          "change-case",
          "小文字・大文字に変換",
          "text.toLowerCase()",
          "すべて小文字にする。大文字にするなら toUpperCase()。",
        ),
        item(
          "normalize",
          "表記ゆれをそろえる",
          'text.normalize("NFKC")',
          "全角英数字や半角カナなどを、標準的な形にそろえる。",
          "検索の前に小文字化と組み合わせると一致しやすくなる。",
          "info",
        ),
        item(
          "regex-test",
          "正規表現で判定",
          "/^\\d{3}-\\d{4}$/.test(zipCode)",
          "文字列が正規表現に一致すれば true を返す。",
        ),
        item(
          "match-all",
          "一致をすべて取り出す",
          "[...text.matchAll(/#(?<tag>\\w+)/g)]",
          "g フラグ付きの正規表現で、一致とキャプチャをすべて取り出す。",
          "名前付きグループは match.groups.tag で参照できる。",
        ),
        item(
          "locale-compare",
          "日本語の順で比較",
          'a.localeCompare(b, "ja")',
          "言語の並び順に従って比較する。",
          'items.sort((a, b) => a.localeCompare(b, "ja")) のように並べ替えに使う。',
        ),
      ],
    },
    // 変換・丸め・表示と、日付・JSON。小数の誤差と月の0始まりは note で必ず触れる。
    {
      id: "numbers-dates-json",
      title: "数値・日付・JSON",
      description: "数値の変換と丸め、日付の表示、JSON との相互変換。",
      items: [
        item(
          "number-convert",
          "数値に変換",
          'Number("42")',
          "文字列全体を数値に変換する。",
          "変換できないと NaN になる。",
        ),
        item(
          "parse-int",
          "先頭の整数を読む",
          'Number.parseInt("08px", 10)',
          "文字列の先頭から、整数として読める部分を取り出す。",
          "基数 10 を明示する。小数は Number.parseFloat()。",
        ),
        item(
          "is-nan",
          "NaN か判定",
          "Number.isNaN(value)",
          "値が NaN のときだけ true を返す。",
          "グローバルの isNaN() は先に型変換するので使わない。",
        ),
        item(
          "float-error",
          "小数の誤差と桁の固定",
          "(0.1 + 0.2).toFixed(2)",
          "小数点以下の桁数を固定した文字列にする。",
          "0.1 + 0.2 は 0.30000000000000004 になる。金額は円やセント単位の整数で計算する。",
        ),
        item(
          "math-round",
          "丸める",
          "Math.round(x) / Math.floor(x) / Math.ceil(x)",
          "四捨五入／切り捨て／切り上げした整数を返す。",
          "Math.floor(-1.5) は -2。0 の方向へ切り捨てるなら Math.trunc()。",
        ),
        item(
          "random-int",
          "ランダムな整数",
          "Math.floor(Math.random() * 10)",
          "0〜9 のランダムな整数を作る。",
          "セキュリティ用途には crypto.getRandomValues() を使う。",
        ),
        item(
          "number-format",
          "桁区切り・通貨で表示",
          'new Intl.NumberFormat("ja-JP", { style: "currency", currency: "JPY" }).format(1234)',
          "ロケールに合わせて数値を整形する。",
          "結果は「￥1,234」。",
        ),
        item(
          "date-create",
          "日付を作る",
          "new Date(2026, 0, 31)",
          "年・月・日を指定して日付を作る。",
          "月は0始まりなので、0 が1月になる。",
        ),
        item(
          "date-format",
          "日付を表示",
          'date.toLocaleDateString("ja-JP")',
          "ロケールに合わせて日付を文字列にする。",
          "保存や送信には date.toISOString()（UTC）を使う。",
        ),
        item(
          "json-stringify",
          "JSON 文字列にする",
          "JSON.stringify(data, null, 2)",
          "値を JSON 文字列に変換する。第3引数でインデントを付ける。",
          "undefined・関数・Symbol のプロパティは出力されない。",
        ),
        item(
          "json-parse",
          "JSON を読み込む",
          "JSON.parse(text)",
          "JSON 文字列をオブジェクトに変換する。",
          "不正な JSON は例外を投げるので try...catch で囲む。",
          "warning",
        ),
      ],
    },
    // クラス構文。非公開フィールド（#）は外から触れないことを推奨として示す。
    {
      id: "classes",
      title: "クラス",
      description: "コンストラクター・メソッド・継承・非公開フィールドの書き方。",
      items: [
        item(
          "class",
          "クラスを定義",
          "class User { constructor(name) { this.name = name; } }",
          "new で呼び出すと、constructor で初期化したインスタンスを作る。",
          "関数宣言と違い、定義より前の行では使えない。",
        ),
        item(
          "method",
          "メソッド",
          "greet() { return `こんにちは、${this.name}さん`; }",
          "インスタンスから呼び出す関数を定義する。",
        ),
        item(
          "class-field",
          "クラスフィールド",
          "count = 0;",
          "インスタンスごとのプロパティを、constructor の外で宣言する。",
        ),
        item(
          "private-field",
          "非公開フィールド",
          "#token = null;",
          "# で始まるフィールドは、クラスの外から参照できない。",
          "外から参照するコードは構文エラーになる。",
          "info",
        ),
        item(
          "getter-setter",
          "getter / setter",
          "get fullName() { return `${this.first} ${this.last}`; }",
          "プロパティのように読み書きできるメソッドを定義する。",
          "書き込み側は set fullName(value) { … }。",
        ),
        item(
          "static",
          "静的メソッド",
          "static fromJSON(json) { … }",
          "インスタンスを作らずに User.fromJSON() のように呼ぶ。",
        ),
        item(
          "extends",
          "継承",
          "class Admin extends User { constructor(name) { super(name); } }",
          "既存のクラスを拡張する。",
          "constructor では this を使う前に super() を呼ぶ。",
        ),
        item(
          "instanceof",
          "インスタンスか判定",
          "value instanceof User",
          "値がそのクラス（またはサブクラス）から作られたか判定する。",
        ),
      ],
    },
    // Promise と async / await。forEach に async を渡す誤りを warning で示す。
    {
      id: "async",
      title: "非同期処理",
      description: "async / await で書き、並行してよい処理は Promise.all でまとめて待つ。",
      items: [
        item(
          "promise",
          "Promise を作る",
          "new Promise((resolve, reject) => { … })",
          "非同期処理の結果を表すオブジェクトを作る。",
          "成功したら resolve(値)、失敗したら reject(エラー) を呼ぶ。",
        ),
        item(
          "then-catch",
          "then / catch / finally",
          "fetchUser().then(render).catch(showError).finally(hideSpinner)",
          "成功・失敗・完了時の処理をつなげる。",
        ),
        item(
          "async-await",
          "async / await",
          "const user = await fetchUser(id);",
          "async 関数の中で、Promise の完了を待って結果を受け取る。",
          "await は async 関数の中か、モジュールの最上位で使える。",
          "info",
        ),
        item(
          "await-try-catch",
          "await のエラー処理",
          "try { await save(); } catch (error) { … }",
          "await した Promise の失敗を try...catch で受け取る。",
        ),
        item(
          "promise-all",
          "並行してすべて待つ",
          "const [user, posts] = await Promise.all([getUser(), getPosts()]);",
          "複数の処理を同時に走らせ、すべての結果を受け取る。",
          "1つでも失敗すると、その時点で全体が失敗になる。",
        ),
        item(
          "promise-all-settled",
          "成否をすべて受け取る",
          "const results = await Promise.allSettled(tasks);",
          "失敗があってもすべての完了を待ち、それぞれの結果を返す。",
          '各結果の status は "fulfilled" か "rejected"。',
        ),
        item(
          "promise-race-any",
          "最初の結果を使う",
          "await Promise.race(tasks) / await Promise.any(tasks)",
          "race は最初に完了したもの、any は最初に成功したものを返す。",
          "any はすべて失敗すると AggregateError になる。",
        ),
        item(
          "sequential-await",
          "順番に待つ",
          "for (const id of ids) { await upload(id); }",
          "1件ずつ完了を待ちながら、順番に処理する。",
          "順序が不要なら、Promise.all で並行にすると速い。",
        ),
        item(
          "foreach-async",
          "forEach に async を渡す",
          "items.forEach(async (item) => { await save(item); });",
          "各要素の処理は始まるが、forEach 自体は完了を待たない。",
          "完了を待つなら for...of か Promise.all を使う。",
          "warning",
        ),
        item(
          "set-timeout",
          "一定時間後に実行",
          "const timer = setTimeout(callback, 1000);",
          "指定したミリ秒の後に、関数を1回実行する。",
          "clearTimeout(timer) で取り消す。繰り返しは setInterval() / clearInterval()。",
        ),
        item(
          "sleep",
          "指定時間待つ",
          "await new Promise((resolve) => setTimeout(resolve, 500));",
          "setTimeout を Promise で包み、async 関数の中で待つ。",
        ),
      ],
    },
    // ES Modules。ブラウザで直接読み込むときの約束（拡張子・type="module"）も含める。
    {
      id: "modules",
      title: "モジュール",
      description: "ファイル単位で export し、使う側で import する。",
      items: [
        item(
          "named-export",
          "名前付き export",
          "export function formatDate(date) { … }",
          "名前を付けて公開する。1ファイルに複数書ける。",
          "export const など、ほかの宣言にも付けられる。",
        ),
        item(
          "named-import",
          "名前付き import",
          'import { formatDate, parseDate } from "./date.js";',
          "名前を指定して読み込む。",
          "ブラウザで直接読み込むときは拡張子まで書く。",
        ),
        item(
          "default-export",
          "default export / import",
          'export default function App() { … }\nimport App from "./App.js";',
          "ファイルの代表を1つだけ公開し、読み込む側で好きな名前を付ける。",
        ),
        item(
          "import-alias",
          "別名で import",
          'import { formatDate as format } from "./date.js";',
          "名前がぶつかるときに別名で読み込む。",
        ),
        item(
          "namespace-import",
          "まとめて import",
          'import * as dateUtils from "./date.js";',
          "公開されたものすべてを、1つのオブジェクトとして読み込む。",
        ),
        item(
          "re-export",
          "再 export",
          'export { formatDate } from "./date.js";',
          "別のファイルのものを、そのまま公開する。",
          "入口のファイルに集めて、import 先を1か所にまとめるときに使う。",
        ),
        item(
          "dynamic-import",
          "動的 import",
          'const { Chart } = await import("./chart.js");',
          "必要になった時点でモジュールを読み込む。",
          "Promise を返すので await する。",
        ),
        item(
          "script-module",
          "モジュールとして読み込む",
          '<script type="module" src="./main.js"></script>',
          "HTML からモジュールとしてスクリプトを読み込む。",
          "defer と同じく HTML の解析後に実行され、strict mode になる。",
        ),
      ],
    },
    // 例外の投げ方と受け方、コンソールでの調査。debugger は残し忘れを警告する。
    {
      id: "errors",
      title: "エラー処理・デバッグ",
      description: "例外は Error オブジェクトで投げ、元の原因は cause でつなぐ。",
      items: [
        item(
          "try-catch",
          "例外を捕まえる",
          "try { … } catch (error) { … } finally { … }",
          "例外が起きたら catch、成否に関係なく最後に finally を実行する。",
        ),
        item(
          "throw",
          "例外を投げる",
          'throw new Error("保存に失敗しました");',
          "処理を中断して例外を投げる。",
          "文字列ではなく Error を投げると、スタックトレースが残る。",
        ),
        item(
          "error-cause",
          "原因をつなげる",
          'throw new Error("設定の読み込みに失敗しました", { cause: error });',
          "元のエラーを cause に入れて投げ直す。",
          "error.cause で元のエラーを参照できる。",
        ),
        item(
          "custom-error",
          "独自のエラークラス",
          'class ValidationError extends Error { name = "ValidationError"; }',
          "Error を継承して、種類を区別できるエラーを作る。",
        ),
        item(
          "error-instanceof",
          "エラーの種類で分岐",
          "if (error instanceof ValidationError) { … }",
          "catch したエラーの種類ごとに処理を分ける。",
          "想定外のエラーは throw error; で投げ直す。",
        ),
        item(
          "console-log",
          "ログを出す",
          "console.log(value) / console.warn(message) / console.error(error)",
          "DevTools のコンソールに出力する。warn と error は目立つ色で表示される。",
        ),
        item(
          "console-table",
          "表で表示",
          "console.table(rows)",
          "配列やオブジェクトを表形式で表示する。",
        ),
        item(
          "console-time",
          "処理時間を計る",
          'console.time("load"); … console.timeEnd("load");',
          "同じラベルの time から timeEnd までの経過時間を表示する。",
        ),
        item(
          "debugger",
          "ブレークポイント",
          "debugger;",
          "DevTools を開いているとき、この行で実行を止める。",
          "本番のコードに残さない。",
          "warning",
        ),
      ],
    },
    // 要素の取得・更新とイベント。innerHTML は XSS の入口になるので danger。
    {
      id: "dom",
      title: "DOM操作・イベント",
      description: "要素を取得して内容を書き換え、イベントで操作に反応する。",
      items: [
        item(
          "query-selector",
          "要素を1つ取得",
          'document.querySelector(".card")',
          "CSS セレクターに一致する最初の要素を返す。",
          "見つからなければ null。",
        ),
        item(
          "query-selector-all",
          "要素をすべて取得",
          'document.querySelectorAll("li")',
          "一致する要素をすべて NodeList で返す。",
          "forEach() は使えるが、map() などは Array.from() で配列にしてから使う。",
        ),
        item(
          "text-content",
          "テキストを設定",
          "el.textContent = message;",
          "文字列をテキストとして設定する。HTML としては解釈されない。",
          undefined,
          "info",
        ),
        item(
          "inner-html",
          "HTML を挿入",
          "el.innerHTML = html;",
          "文字列を HTML として解釈し、中身を置き換える。",
          "ユーザー入力を入れると XSS になる。テキストは textContent で設定する。",
          "danger",
          ["xss", "セキュリティ"],
        ),
        item(
          "create-element",
          "要素を作って追加",
          'const li = document.createElement("li");\nlist.append(li);',
          "要素を作成し、子要素の末尾に追加する。",
          "先頭に追加するなら prepend()。",
        ),
        item("remove-element", "要素を削除", "el.remove();", "要素を DOM から取り除く。"),
        item(
          "class-list",
          "クラスを付け外し",
          'el.classList.toggle("is-open")',
          "クラスの付け外しを切り替える。",
          "add() / remove() / contains() もある。",
        ),
        item(
          "dataset",
          "data 属性を読み書き",
          "el.dataset.userId",
          "data-user-id 属性の値を読み書きする。",
          "ハイフン区切りの名前は、キャメルケースで参照する。",
        ),
        item(
          "set-attribute",
          "属性を設定",
          'button.setAttribute("aria-expanded", "true")',
          "任意の属性を設定する。",
          "取得は getAttribute()、削除は removeAttribute()。",
        ),
        item(
          "style-property",
          "CSS 変数を設定",
          'el.style.setProperty("--accent", color)',
          "インラインスタイルで CSS カスタムプロパティを設定する。",
        ),
        item(
          "add-event-listener",
          "イベントを登録",
          'button.addEventListener("click", handleClick);',
          "イベントが起きたときに実行する関数を登録する。",
          "解除するときは、同じ関数を removeEventListener() に渡す。",
        ),
        item(
          "listener-once",
          "1回だけ反応",
          'el.addEventListener("click", handleClick, { once: true });',
          "最初の1回だけ実行し、自動で登録を解除する。",
        ),
        item(
          "prevent-default",
          "既定の動作を止める",
          "event.preventDefault();",
          "フォーム送信やリンク遷移など、ブラウザ既定の動作を止める。",
        ),
        item(
          "event-delegation",
          "イベント委譲",
          'list.addEventListener("click", (event) => { const item = event.target.closest("li"); … });',
          "親要素でまとめて受け取り、closest() で対象の要素を特定する。",
          "後から追加した子要素にも効く。",
        ),
      ],
    },
    // 通信・URL・保存などのブラウザ API。fetch は HTTP エラーで reject しない点を warning にする。
    {
      id: "web-apis",
      title: "fetch・ストレージ",
      description: "HTTP 通信、URL、ブラウザへの保存、クリップボードなどの API。",
      items: [
        item(
          "fetch-get",
          "データを取得",
          'const res = await fetch("/api/items");',
          "HTTP リクエストを送り、レスポンスを受け取る。",
        ),
        item(
          "fetch-ok",
          "失敗を判定",
          "if (!res.ok) throw new Error(`HTTP ${res.status}`);",
          "ステータスが 200〜299 以外なら、自分でエラーにする。",
          "fetch は 404 や 500 でも reject しない。",
          "warning",
        ),
        item(
          "response-json",
          "JSON として読む",
          "const data = await res.json();",
          "レスポンスの本文を JSON として解析する。",
          "テキストは res.text()。本文は一度しか読めない。",
        ),
        item(
          "fetch-post",
          "JSON を送信",
          `await fetch("/api/items", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify(item),
});`,
          "メソッド・ヘッダー・本文を指定して送信する。",
        ),
        item(
          "abort-timeout",
          "タイムアウトで中断",
          "await fetch(url, { signal: AbortSignal.timeout(5000) });",
          "指定したミリ秒を過ぎたら、リクエストを中断する。",
          "任意のタイミングで中断するなら AbortController を使う。",
        ),
        item(
          "url-search-params",
          "クエリ文字列を読む",
          'new URLSearchParams(location.search).get("q")',
          "URL の ?q=... から値を取り出す。",
          "値は自動でデコードされる。",
        ),
        item(
          "url",
          "URL を組み立てる",
          'const url = new URL("/search", location.origin);\nurl.searchParams.set("q", keyword);',
          "URL を分解・組み立てる。値のエンコードも任せられる。",
        ),
        item(
          "local-storage",
          "ブラウザに保存",
          'localStorage.setItem("theme", "dark");\nlocalStorage.getItem("theme");',
          "タブを閉じても残る領域に、文字列を保存する。",
          "文字列しか保存できず、使えない環境では例外になるので try...catch で囲む。秘密情報は置かない。",
          "warning",
        ),
        item(
          "storage-json",
          "オブジェクトを保存",
          'localStorage.setItem("cart", JSON.stringify(cart));',
          "JSON 文字列に変換して保存する。",
          "読むときは JSON.parse() で元に戻す。",
        ),
        item(
          "session-storage",
          "タブを閉じるまで保存",
          'sessionStorage.setItem("draft", text);',
          "タブを閉じると消える領域に保存する。",
        ),
        item(
          "clipboard",
          "クリップボードにコピー",
          "await navigator.clipboard.writeText(text);",
          "文字列をクリップボードにコピーする。",
          "HTTPS などの安全なコンテキストでだけ使える。",
        ),
        item(
          "match-media",
          "メディアクエリを判定",
          'matchMedia("(prefers-color-scheme: dark)").matches',
          "メディアクエリに一致するかを JavaScript で判定する。",
          "変化を監視するなら change イベントを登録する。",
        ),
      ],
    },
  ],
};
