import { item } from "../helpers";
import type { CheatSheet } from "../types";

export const gitCheatSheet: CheatSheet = {
  id: "git-reference",
  slug: "git",
  title: "Git チートシート",
  shortTitle: "Git",
  description:
    "日常操作、ブランチ、リモート、履歴調査、安全な取り消しまでをまとめたGitリファレンス。",
  eyebrow: "Version control",
  accent: "#f05033",
  keywords: ["git", "バージョン管理", "commit", "branch", "rebase", "stash"],
  updatedAt: "2026-08-18",
  sources: [{ label: "Git公式リファレンス", url: "https://git-scm.com/docs" }],
  sections: [
    {
      id: "setup",
      title: "初期設定・リポジトリ開始",
      description: "ユーザー情報を設定し、新規作成または複製する。",
      items: [
        item(
          "config-name",
          "ユーザー名",
          'git config --global user.name "Your Name"',
          "コミット作者名を設定する。",
        ),
        item(
          "config-email",
          "メールアドレス",
          'git config --global user.email "you@example.com"',
          "コミット作者メールを設定する。",
        ),
        item(
          "default-branch",
          "既定ブランチ",
          "git config --global init.defaultBranch main",
          "今後のgit initでmainを既定にする。",
        ),
        item(
          "config-list",
          "設定一覧と出所",
          "git config --list --show-origin",
          "どの設定ファイルから来た値か確認する。",
        ),
        item("init", "新規作成", "git init -b main", "現在のディレクトリをGitリポジトリにする。"),
        item("clone", "複製", "git clone <url>", "履歴とリモート設定を取得する。"),
        item(
          "shallow-clone",
          "浅い複製",
          "git clone --depth 1 <url>",
          "最新履歴だけを取得する。",
          "完全化はgit fetch --unshallow。",
          "info",
        ),
        item("version", "バージョン確認", "git --version", "実行環境のGitバージョンを表示する。"),
        item("help", "ヘルプ", "git help <command>", "コマンドの公式マニュアルを表示する。"),
      ],
    },
    {
      id: "daily",
      title: "日常の変更・コミット",
      description: "状態と差分を確認し、小さな単位で履歴へ記録する。",
      items: [
        item(
          "status",
          "状態を確認",
          "git status",
          "現在ブランチ、変更、ステージ状況を表示する。",
          undefined,
          "info",
        ),
        item(
          "status-short",
          "短い状態表示",
          "git status -sb",
          "ブランチと変更をコンパクトに表示する。",
        ),
        item(
          "add-file",
          "ファイルをステージ",
          "git add <file>",
          "指定ファイルの変更を次のコミット対象にする。",
        ),
        item(
          "add-patch",
          "対話的にステージ",
          "git add -p",
          "変更を小さな単位で選択する。",
          undefined,
          "info",
        ),
        item("add-all", "すべてステージ", "git add -A", "新規・変更・削除をすべて対象にする。"),
        item("diff", "未ステージ差分", "git diff", "作業ツリーとステージを比較する。"),
        item(
          "diff-staged",
          "ステージ済み差分",
          "git diff --staged",
          "ステージとHEADを比較する。",
          undefined,
          "info",
        ),
        item("diff-head", "全差分", "git diff HEAD", "作業ツリーと最新コミットを比較する。"),
        item("diff-check", "空白エラー", "git diff --check", "末尾空白などを検出する。"),
        item("commit", "コミット", 'git commit -m "message"', "ステージ済み変更を履歴へ記録する。"),
        item(
          "commit-all",
          "追跡済み変更を一括",
          'git commit -am "message"',
          "追跡済みファイルの変更・削除をまとめて記録する。",
          "新規ファイルは含まれない。",
          "warning",
        ),
        item(
          "amend",
          "直前コミットを修正",
          "git commit --amend",
          "内容やメッセージを修正する。",
          "コミットIDが変わる。",
          "warning",
        ),
      ],
    },
    {
      id: "branches",
      title: "ブランチ",
      description: "独立した作業線を作成・切り替え・整理する。",
      items: [
        item("branch-list", "一覧", "git branch", "ローカルブランチを表示する。"),
        item(
          "branch-all",
          "リモート含む一覧",
          "git branch -a",
          "ローカルとリモート追跡ブランチを表示する。",
        ),
        item("branch-vv", "追跡情報付き一覧", "git branch -vv", "upstreamと進み／遅れを確認する。"),
        item(
          "branch-current",
          "現在名だけ",
          "git branch --show-current",
          "現在ブランチ名を表示する。",
        ),
        item("switch", "切り替え", "git switch <branch>", "指定ブランチへ切り替える。"),
        item(
          "switch-create",
          "作成して切り替え",
          "git switch -c feature/name",
          "現在位置から新規ブランチを作る。",
        ),
        item(
          "switch-track",
          "リモートを追跡",
          "git switch -c feature --track origin/feature",
          "upstreamを明示して作成する。",
        ),
        item("switch-back", "直前ブランチへ", "git switch -", "2ブランチ間をすばやく往復する。"),
        item("branch-rename", "名前変更", "git branch -m new-name", "現在のブランチ名を変更する。"),
        item(
          "branch-delete",
          "安全に削除",
          "git branch -d feature/name",
          "マージ済みブランチを削除する。",
        ),
        item(
          "branch-force-delete",
          "強制削除",
          "git branch -D feature/name",
          "未マージでもブランチ参照を削除する。",
          "履歴を失う可能性がある。",
          "danger",
        ),
        item(
          "detach",
          "コミットを一時閲覧",
          "git switch --detach <commit>",
          "ブランチを動かさず指定コミットを見る。",
        ),
      ],
    },
    {
      id: "integrate",
      title: "マージ・リベース",
      description: "履歴を結合するか、別の基点へ積み直す。",
      items: [
        item(
          "merge",
          "現在ブランチへ統合",
          "git merge <branch>",
          "指定ブランチの履歴を現在ブランチへ統合する。",
        ),
        item(
          "merge-no-ff",
          "マージコミットを残す",
          "git merge --no-ff <branch>",
          "fast-forward可能でもマージコミットを作る。",
        ),
        item(
          "merge-squash",
          "変更だけまとめる",
          "git merge --squash <branch>",
          "統合内容をステージする。",
          "別途git commitが必要。",
        ),
        item("merge-abort", "マージ中止", "git merge --abort", "マージ開始前の状態へ戻す。"),
        item(
          "rebase",
          "基点を積み直す",
          "git rebase main",
          "現在ブランチのコミットをmainの上へ積み直す。",
          "公開済み共有履歴では原則避ける。",
          "warning",
        ),
        item(
          "rebase-interactive",
          "対話的に整理",
          "git rebase -i HEAD~5",
          "並べ替え、squash、fixup、rewordを行う。",
          "コミットIDが変わる。",
          "warning",
        ),
        item(
          "rebase-continue",
          "リベース継続",
          "git rebase --continue",
          "競合解消してgit addした後に続ける。",
        ),
        item("rebase-abort", "リベース中止", "git rebase --abort", "元のブランチ状態へ戻す。"),
        item(
          "cherry-pick",
          "コミットを適用",
          "git cherry-pick <commit>",
          "指定コミットの変更を現在ブランチへ適用する。",
        ),
        item("cherry-abort", "Cherry-pick中止", "git cherry-pick --abort", "開始前の状態へ戻す。"),
      ],
    },
    {
      id: "remote",
      title: "リモート・共有",
      description: "共有リポジトリから取得し、ローカルの履歴を公開する。",
      items: [
        item("remote-list", "リモート一覧", "git remote -v", "fetch／push URLを確認する。"),
        item(
          "remote-add",
          "追加",
          "git remote add origin <url>",
          "originという名前でリモートを登録する。",
        ),
        item(
          "remote-url",
          "URL変更",
          "git remote set-url origin <url>",
          "登録済みリモートURLを変更する。",
        ),
        item(
          "remote-show",
          "詳細確認",
          "git remote show origin",
          "追跡ブランチや既定push先を確認する。",
        ),
        item(
          "fetch",
          "取得",
          "git fetch origin",
          "リモート履歴を取得する。",
          "作業ツリーは変更しない。",
          "info",
        ),
        item(
          "fetch-prune",
          "全取得＋掃除",
          "git fetch --all --prune",
          "削除済みリモート追跡参照も整理する。",
        ),
        item(
          "pull-ff",
          "Fast-forward限定pull",
          "git pull --ff-only",
          "意図しないマージコミットを防ぐ。",
          undefined,
          "info",
        ),
        item(
          "pull-rebase",
          "リベースでpull",
          "git pull --rebase",
          "ローカルコミットを取得履歴の上へ積み直す。",
        ),
        item(
          "push-first",
          "初回push＋追跡設定",
          "git push -u origin feature/name",
          "以後はgit pushだけで送信できる。",
        ),
        item("push", "通常push", "git push", "upstream設定済みブランチを共有する。"),
        item(
          "push-delete",
          "リモートブランチ削除",
          "git push origin --delete feature/name",
          "共有先からブランチ参照を削除する。",
          undefined,
          "warning",
        ),
        item(
          "force-lease",
          "履歴を書き換えてpush",
          "git push --force-with-lease",
          "他者更新がないことを条件に強制pushする。",
          "共有履歴を書き換える。",
          "danger",
        ),
      ],
    },
    {
      id: "undo",
      title: "取り消し・復元",
      description: "残したい場所を確認してから、適切なコマンドを選ぶ。",
      items: [
        item(
          "unstage",
          "ステージだけ解除",
          "git restore --staged <file>",
          "作業中の変更を残してステージだけ外す。",
          undefined,
          "info",
        ),
        item(
          "discard-file",
          "未ステージ変更を破棄",
          "git restore <file>",
          "ファイルをステージ内容へ戻す。",
          "未コミット変更が消える。",
          "danger",
        ),
        item(
          "restore-source",
          "指定コミット版を復元",
          "git restore --source=<commit> -- <file>",
          "別コミットのファイル内容を作業ツリーへ取り出す。",
          "現在内容を上書きする。",
          "warning",
        ),
        item(
          "reset-soft",
          "直前コミットを戻しステージ維持",
          "git reset --soft HEAD~1",
          "HEADだけを1つ戻す。",
          "履歴が変わる。",
          "warning",
        ),
        item(
          "reset-mixed",
          "直前コミットを戻し未ステージへ",
          "git reset HEAD~1",
          "HEADとステージを戻し、変更は作業ツリーへ残す。",
          "履歴が変わる。",
          "warning",
        ),
        item(
          "reset-hard",
          "コミットと変更を破棄",
          "git reset --hard <commit>",
          "HEAD・ステージ・作業ツリーを一致させる。",
          "追跡済み未コミット変更が消える。",
          "danger",
        ),
        item(
          "revert",
          "公開コミットを打ち消す",
          "git revert <commit>",
          "逆変更を新しいコミットとして追加する。",
          "共有履歴向け。",
          "info",
        ),
        item(
          "reflog",
          "消えたコミットを探す",
          "git reflog",
          "HEAD移動履歴からコミットハッシュを探す。",
          undefined,
          "info",
        ),
        item(
          "rescue",
          "見つけたコミットを救出",
          "git switch -c rescue <commit>",
          "新規ブランチとしてコミットを保護する。",
          undefined,
          "info",
        ),
      ],
    },
    {
      id: "stash",
      title: "一時退避（stash）",
      description: "未完成の変更をコミットせずに一時保存する。",
      items: [
        item(
          "stash-push",
          "メッセージ付き退避",
          'git stash push -m "WIP: login"',
          "追跡済み変更を退避する。",
        ),
        item(
          "stash-untracked",
          "未追跡も退避",
          'git stash push -u -m "WIP"',
          "未追跡ファイルも含めて退避する。",
        ),
        item("stash-patch", "対話的に退避", "git stash push -p", "退避する変更を選択する。"),
        item("stash-list", "一覧", "git stash list", "stashエントリーを表示する。"),
        item(
          "stash-show",
          "内容確認",
          "git stash show -p stash@{0}",
          "最新stashの差分を表示する。",
        ),
        item(
          "stash-apply",
          "適用して残す",
          "git stash apply stash@{0}",
          "作業ツリーへ適用し、stash一覧には残す。",
        ),
        item(
          "stash-pop",
          "適用して削除",
          "git stash pop",
          "適用に成功したstashを一覧から削除する。",
          "競合する可能性がある。",
          "warning",
        ),
        item(
          "stash-branch",
          "stashからブランチ",
          "git stash branch wip-login stash@{0}",
          "退避時点から新しいブランチで再開する。",
        ),
        item(
          "stash-drop",
          "1件削除",
          "git stash drop stash@{0}",
          "指定stashを削除する。",
          undefined,
          "warning",
        ),
        item(
          "stash-clear",
          "全件削除",
          "git stash clear",
          "すべてのstash参照を削除する。",
          "復元が困難。",
          "danger",
        ),
      ],
    },
    {
      id: "history",
      title: "履歴・差分・検索",
      description: "変更のいつ・誰が・どこを・なぜを調査する。",
      items: [
        item(
          "log-graph",
          "見やすい全体履歴",
          "git log --oneline --graph --decorate --all",
          "ブランチ構造を俯瞰する。",
        ),
        item("log-recent", "最近5件", "git log -5 --oneline", "直近コミットだけを表示する。"),
        item("show", "コミット詳細", "git show <commit>", "メッセージと差分を表示する。"),
        item(
          "log-follow",
          "ファイル履歴",
          "git log --follow -- <file>",
          "名前変更を追いながら履歴を表示する。",
        ),
        item(
          "log-patch",
          "ファイル履歴＋差分",
          "git log -p -- <file>",
          "各コミットの変更内容を表示する。",
        ),
        item(
          "log-author",
          "作者で絞る",
          'git log --author="name"',
          "作者名・メールを正規表現で照合する。",
        ),
        item(
          "log-since",
          "期間で絞る",
          'git log --since="2 weeks ago"',
          "指定期間以降のコミットを表示する。",
        ),
        item(
          "log-grep",
          "メッセージ検索",
          'git log --grep="fix"',
          "コミットメッセージを検索する。",
        ),
        item(
          "log-pickaxe",
          "文字列の増減を検索",
          'git log -S "featureFlag" --all',
          "文字列の出現回数が変わったコミットを探す。",
        ),
        item(
          "log-regex",
          "差分を正規表現検索",
          'git log -G "pattern" --all',
          "差分行が正規表現に一致するコミットを探す。",
        ),
        item(
          "grep",
          "追跡ファイル内検索",
          'git grep -n "TODO"',
          "追跡中ファイルを行番号付きで検索する。",
        ),
        item(
          "blame",
          "行の最終変更者",
          "git blame -L 10,30 <file>",
          "指定範囲を最後に変更したコミットを調べる。",
        ),
        item(
          "show-file",
          "コミット時点のファイル",
          "git show <commit>:<path>",
          "作業ツリーを変えずに内容を表示する。",
        ),
        item(
          "diff-branch",
          "分岐点からの差分",
          "git diff main...HEAD",
          "共通祖先から現在ブランチまでを比較する。",
        ),
      ],
    },
    {
      id: "conflicts",
      title: "競合の解消",
      description: "競合箇所を編集し、解決済みとして登録して処理を続ける。",
      items: [
        item(
          "conflict-status",
          "競合状態を確認",
          "git status",
          "競合ファイルと次に実行する操作を確認する。",
          undefined,
          "info",
        ),
        item(
          "conflict-list",
          "競合ファイル一覧",
          "git diff --name-only --diff-filter=U",
          "未マージのファイルだけ表示する。",
        ),
        item(
          "conflict-stage",
          "解決済みにする",
          "git add <resolved-file>",
          "マーカーを除去して内容確認後にステージする。",
        ),
        item(
          "merge-continue",
          "マージ継続",
          "git merge --continue",
          "すべて解決後にマージを完了する。",
        ),
        item(
          "rebase-continue-conflict",
          "リベース継続",
          "git rebase --continue",
          "解決済みコミットからリベースを再開する。",
        ),
        item(
          "ours",
          "こちら側を採用",
          "git restore --ours <file>",
          "競合ファイルでours側を採用する。",
          "リベース中は意味に注意。",
          "warning",
        ),
        item(
          "theirs",
          "相手側を採用",
          "git restore --theirs <file>",
          "競合ファイルでtheirs側を採用する。",
          "内容確認後にgit add。",
          "warning",
        ),
        item("mergetool", "解消ツール", "git mergetool", "設定済みの競合解消ツールを起動する。"),
      ],
    },
    {
      id: "files-tags-tools",
      title: "ファイル・タグ・調査ツール",
      description: "無視設定、タグ、バグ混入調査、複数作業ツリー。",
      items: [
        item(
          "check-ignore",
          "無視理由を確認",
          "git check-ignore -v <file>",
          "どの.gitignoreルールが一致したか表示する。",
        ),
        item(
          "rm",
          "削除してステージ",
          "git rm <file>",
          "作業ツリーから削除し、削除をステージする。",
        ),
        item(
          "rm-cached",
          "追跡だけ解除",
          "git rm --cached <file>",
          "手元のファイルを残してindexから外す。",
        ),
        item("mv", "移動・名前変更", "git mv <old> <new>", "移動とステージをまとめて行う。"),
        item(
          "clean-preview",
          "未追跡削除を予行",
          "git clean -nd",
          "削除対象だけを表示する。",
          "実行前に必ず使う。",
          "info",
        ),
        item(
          "clean",
          "未追跡を削除",
          "git clean -fd",
          "未追跡ファイル・ディレクトリを削除する。",
          "通常のGit復元対象外。",
          "danger",
        ),
        item(
          "tag",
          "注釈付きタグ",
          'git tag -a v1.2.0 -m "Release v1.2.0"',
          "作成者・日時・メッセージを持つタグを作る。",
        ),
        item("tag-push", "タグをpush", "git push origin v1.2.0", "指定タグをリモートへ送る。"),
        item(
          "tag-delete",
          "リモートタグ削除",
          "git push origin --delete v1.2.0",
          "共有タグを削除する。",
          undefined,
          "warning",
        ),
        item(
          "bisect",
          "バグ混入を二分探索",
          "git bisect start HEAD v1.0.0",
          "異常地点と正常地点の間を効率よく絞る。",
        ),
        item(
          "bisect-run",
          "テストを自動実行",
          "git bisect run ./test-script.sh",
          "終了コードを使ってgood／badを自動判定する。",
        ),
        item("bisect-reset", "二分探索を終了", "git bisect reset", "開始前のHEADへ戻る。"),
        item(
          "worktree",
          "別作業ツリー追加",
          "git worktree add ../hotfix -b hotfix main",
          "stashせず別ブランチを並行作業する。",
        ),
        item(
          "worktree-list",
          "作業ツリー一覧",
          "git worktree list",
          "パス・ブランチ・HEADを表示する。",
        ),
        item(
          "submodule",
          "Submodule初期化",
          "git submodule update --init --recursive",
          "入れ子のsubmoduleも取得する。",
        ),
        item(
          "archive",
          "ソースをzip化",
          "git archive --format=zip -o source.zip HEAD",
          ".gitを含めず指定時点のファイルを出力する。",
        ),
      ],
    },
  ],
};
