/**
 * CSSチートシートのデータ。
 *
 * 表示側（components）はこの構造だけを見るので、ここに書いた順序がそのまま
 * 目次とページの並び順になる。項目は必ず helpers.ts の item() で生成する。
 *
 *   item(id, label, syntax, description, note?, status?, keywords?)
 *
 * - id はシート内で一意。目次のアンカー（#id）とReactのkeyに使われる
 * - status は normal / info / warning / danger。省略時は normal
 * - フォーカスの表示を消す、見た目と読み上げの順番をずらすなど、アクセシビリティを損なう書き方と、
 *   後から上書きしにくくなる書き方には warning、推奨の書き方には info を付ける。
 *   バッジの色が唯一の警告表示になるため、付け忘れると危険が伝わらない
 * - 範囲は CSS 本体だけ（Sass・Tailwind などは扱わない）
 * - 新しい機能は、主要ブラウザ（Chrome・Edge・Firefox・Safari）の対応状況を note に書く。
 *   「すべての主要ブラウザが対応」は Baseline に入ったもの。対応状況は webstatus.dev と
 *   MDN の互換性データで確認済み（2026-09-19）
 * - keywords は検索用の別名。全角/半角・大文字小文字は normalizeSearch が吸収する
 * - 内容を直したら updatedAt も更新する
 */
import { item } from "../helpers";
import type { CheatSheet } from "../types";

export const cssCheatSheet: CheatSheet = {
  id: "css-reference",
  slug: "css",
  title: "CSS チートシート",
  name: "CSS",
  description:
    "セレクターとカスケード、ボックスモデル、Flexbox・Grid、配置、文字と色、レスポンシブ、アニメーション、:has() や @layer などの新しい機能までをまとめたCSSリファレンス。",
  eyebrow: "Style sheet language",
  // CSS の公式ロゴの色（rebeccapurple）。そのままではダークの背景で暗すぎて読みにくいので、
  // ダークでは明るい紫にする。
  accent: "light-dark(#663399, #9d6fe0)",
  keywords: ["css", "スタイル", "スタイルシート", "stylesheet", "レイアウト", "デザイン"],
  updatedAt: "2026-09-20",
  sources: [
    { label: "MDN CSS", url: "https://developer.mozilla.org/ja/docs/Web/CSS" },
    { label: "Web Platform Status（Baseline）", url: "https://webstatus.dev/" },
  ],
  sections: [
    // ルールの書き方と、HTML への読み込み方。ネストもここで扱う。
    {
      id: "basics",
      title: "書き方・読み込み",
      description: "ルールの書き方、ネスト、HTML への読み込み方。",
      items: [
        item(
          "rule",
          "ルールの書き方",
          "h1 {\n  color: #333;\n  font-size: 2rem;\n}",
          "セレクターで選んだ要素に、プロパティと値の組を指定する。",
          "宣言と宣言の間は ; で区切る。",
        ),
        item(
          "comment",
          "コメント",
          "/* ここはコメント */",
          "/* と */ の間は無視される。",
          "// の1行コメントは使えない。",
        ),
        item(
          "nesting",
          "ネスト",
          ".card {\n  padding: 1rem;\n\n  .title {\n    font-weight: 700;\n  }\n}",
          "ルールの中に、子孫のルールを入れ子にして書く。",
          "すべての主要ブラウザが対応。Sass と違い、ビルドしなくてもそのまま動く。",
          "normal",
          ["入れ子", "nesting"],
        ),
        item(
          "nesting-ampersand",
          "& で外側を指す",
          ".button {\n  &:hover { opacity: 0.8; }\n  &.is-active { color: #663399; }\n  .dark & { color: #eee; }\n}",
          "& は外側のセレクターを指す。擬似クラスを付けるときや、クラスを重ねるときに使う。",
          "&-title のように名前をつなげる書き方（Sass の機能）はできない。",
        ),
        item(
          "nesting-media",
          "ルールの中に条件を書く",
          ".sidebar {\n  display: none;\n\n  @media (width >= 1024px) {\n    display: block;\n  }\n}",
          "ルールの中に @media や @container を書き、条件に合うときだけ値を変える。",
        ),
        item(
          "link",
          "CSS ファイルを読み込む",
          '<link rel="stylesheet" href="/css/style.css">',
          "HTML の head に書き、CSS ファイルを読み込む。",
          "複数のページで共有でき、ブラウザがキャッシュする。",
          "info",
        ),
        item(
          "style-element",
          "HTML の中に書く",
          "<style>\n  p { line-height: 1.8; }\n</style>",
          "head の style 要素に、そのページだけで使う CSS を書く。",
        ),
        item(
          "inline-style",
          "要素に直接書く",
          '<p style="color: red;">…</p>',
          "style 属性で、その要素だけに指定する。",
          "ほかのルールより優先され、CSS ファイルから上書きしにくい。JavaScript で動的に変える値などに限る。",
          "warning",
        ),
        item(
          "import",
          "別の CSS を読み込む",
          '@import url("reset.css") layer(reset);',
          "CSS の中から別の CSS を読み込む。layer() を付けると、カスケードレイヤーに入れられる。",
          "ファイルの先頭に書く。読み込みが順番待ちになって表示が遅れやすいので、link を並べるか、ビルドツールで1つにまとめる。",
        ),
      ],
    },
    // 要素の選び方。結合子と、:is() / :has() などの関数の形の擬似クラス。
    {
      id: "selectors",
      title: "セレクター",
      description: "スタイルを当てる要素の選び方。",
      items: [
        item(
          "basic-selectors",
          "要素・クラス・ID",
          "p { }\n.card { }\n#main { }",
          "要素名、クラス（.）、ID（#）で要素を選ぶ。",
          "ID は詳細度が高く上書きしにくいので、スタイルにはクラスを使う。",
          "normal",
          ["class", "id"],
        ),
        item("universal", "すべての要素", "* { margin: 0; }", "* はすべての要素に一致する。"),
        item(
          "grouping",
          "まとめて指定",
          "h1, h2, h3 { line-height: 1.3; }",
          "カンマで区切ると、どれかに一致する要素に同じスタイルを当てる。",
        ),
        item(
          "descendant-child",
          "子孫・子",
          ".nav a { }\n.nav > li { }",
          "空白は中にある要素すべて、> は直下の子だけに一致する。",
          undefined,
          "normal",
          ["結合子", "combinator"],
        ),
        item(
          "sibling",
          "兄弟",
          "h2 + p { }\nh2 ~ p { }",
          "+ は直後の兄弟1つ、~ は後ろにある兄弟すべてに一致する。",
        ),
        item(
          "attribute",
          "属性",
          'a[href^="https://"] { }\ninput[type="email"] { }',
          "属性の有無や値で選ぶ。^= は前方一致、$= は後方一致、*= は部分一致。",
        ),
        item(
          "is-where",
          ":is()・:where()",
          ":is(h1, h2, h3) a { }\n:where(ul, ol) { list-style: none; }",
          "かっこの中のどれかに一致する要素を選ぶ。",
          ":where() は詳細度が 0 になるので、後から上書きしやすい既定のスタイルに向く。",
        ),
        item(
          "not",
          ":not()",
          "li:not(:last-child) {\n  border-bottom: 1px solid #ddd;\n}",
          "かっこの中に一致しない要素を選ぶ。",
        ),
        item(
          "has",
          ":has()",
          ".card:has(img) { }\nlabel:has(+ input:user-invalid) { }",
          "中や後ろに特定の要素がある要素を選ぶ。親や前の兄弟を条件で選べる。",
          "すべての主要ブラウザが対応。",
          "normal",
          ["親セレクター", "parent selector"],
        ),
        item(
          "nth-child",
          "n 番目",
          "li:nth-child(2n + 1) { }\ntr:nth-child(even) { }",
          "兄弟の中で n 番目の要素を選ぶ。odd は奇数番目、even は偶数番目。",
          ":nth-child(2 of .item) と書くと、.item の中だけで数える。",
        ),
        item(
          "first-last",
          "最初・最後",
          "li:first-child { }\nli:last-child { }\np:only-child { }",
          "兄弟の中で最初、最後、1つだけの要素を選ぶ。",
          "同じ種類の要素の中で数えるなら :first-of-type、:last-of-type。",
        ),
      ],
    },
    // 操作や入力の状態で選ぶ擬似クラスと、要素の一部を選ぶ擬似要素。
    {
      id: "pseudo",
      title: "擬似クラス・擬似要素",
      description: "操作や入力の状態で選ぶ擬似クラスと、要素の一部を選ぶ擬似要素。",
      items: [
        item(
          "hover",
          ":hover",
          "a:hover { text-decoration: none; }",
          "マウスが乗っている要素に一致する。",
          "タッチ操作ではうまく働かない。マウスのある環境だけに当てるなら @media (hover: hover) で囲む。",
        ),
        item(
          "focus-visible",
          ":focus-visible",
          "button:focus-visible {\n  outline: 2px solid #663399;\n  outline-offset: 2px;\n}",
          "キーボードで操作しているときなど、フォーカスを見せるべきときだけ一致する。",
          "マウスでクリックしたときは枠を出さず、キーボードのときだけ出せる。",
          "info",
          ["フォーカス", "focus"],
        ),
        item(
          "focus-within",
          ":focus-within",
          ".field:focus-within { border-color: #663399; }",
          "中の要素のどれかにフォーカスがあるときに一致する。",
        ),
        item(
          "form-states",
          ":checked・:disabled",
          "input:checked + label { }\nbutton:disabled { opacity: 0.5; }",
          "チェックされた入力と、使えない状態のフォーム部品に一致する。",
        ),
        item(
          "user-invalid",
          ":user-invalid",
          "input:user-invalid { border-color: #c00; }",
          "ユーザーが入力したあとで、値が正しくない入力欄に一致する。",
          ":invalid は入力する前から一致するので、ページを開いたとたんにエラーの表示になる。",
          "info",
          ["バリデーション", "validation"],
        ),
        item(
          "target",
          ":target",
          ":target { background: #fff3c4; }",
          "URL の #id と同じ id を持つ要素に一致する。",
        ),
        item(
          "before-after",
          "::before・::after",
          '.required::after {\n  content: "*";\n  color: #c00;\n}',
          "要素の中の先頭・末尾に、飾りの内容を足す。",
          "content が無いと表示されない。読み上げでの扱いがブラウザによって違うので、意味のある文章は HTML に書く。",
          "normal",
          ["擬似要素", "content"],
        ),
        item(
          "placeholder",
          "::placeholder",
          "input::placeholder { color: #767676; }",
          "入力欄のプレースホルダーの文字を選ぶ。",
          "薄くしすぎると読めなくなる。背景との明るさの差（コントラスト）を保つ。",
        ),
        item(
          "marker",
          "::marker",
          "li::marker { color: #663399; }",
          "リストの先頭の記号や番号を選ぶ。",
        ),
        item(
          "selection",
          "::selection",
          "::selection { background: #e0d4f5; }",
          "ユーザーが選択した範囲の文字を選ぶ。",
        ),
      ],
    },
    // 同じ要素に複数のルールが当たったときの優先順位。
    {
      id: "cascade",
      title: "カスケード・詳細度",
      description: "同じ要素に複数のルールが当たったとき、どれが優先されるかの決まり。",
      items: [
        item(
          "specificity",
          "詳細度",
          "/* (1, 0, 0) */\n#main { }\n/* (0, 2, 0) */\n.card:hover { }\n/* (0, 0, 3) */\nul li::marker { }",
          "ID・クラス（擬似クラス、属性を含む）・要素（擬似要素を含む）の数を左の桁から比べ、大きいほうのルールが優先される。",
          "詳細度が同じなら、後に書いたルールが優先される。",
          "normal",
          ["specificity", "優先順位"],
        ),
        item(
          "important",
          "!important",
          "color: red !important;",
          "詳細度に関係なく、その宣言を優先させる。",
          "上書きするには、さらに !important が要るようになる。外部の CSS を上書きするときなどに限る。",
          "warning",
        ),
        item(
          "layer-order",
          "レイヤーの順番を決める",
          "@layer reset, base, components, utilities;",
          "カスケードレイヤーの順番を宣言する。後に書いたレイヤーほど優先される。",
          "レイヤーの間では詳細度より順番が優先されるので、詳細度の競い合いにならない。レイヤーに入れていないスタイルは、どのレイヤーよりも優先される。",
          "info",
          ["cascade layers", "カスケードレイヤー"],
        ),
        item(
          "layer-block",
          "レイヤーに入れる",
          "@layer components {\n  .card { padding: 1rem; }\n}",
          "ブロックの中のルールを、指定したレイヤーに入れる。",
        ),
        item(
          "scope",
          "@scope",
          "@scope (.card) to (.card-body) {\n  img { border-radius: 8px; }\n}",
          "スタイルを当てる範囲を、ある要素の中に限る。to に書いた要素から先は含まない。",
          "すべての主要ブラウザが対応（2026年3月から）。",
        ),
        item(
          "inheritance",
          "継承",
          "body {\n  color: #333;\n  font-family: system-ui, sans-serif;\n}",
          "文字の色やフォントなど一部のプロパティは、親から子へ引き継がれる。",
          "margin、padding、border などは継承されない。",
        ),
        item(
          "css-wide-keywords",
          "継承や既定値に戻す",
          "color: inherit;\ncolor: initial;\ncolor: unset;\ncolor: revert;",
          "inherit は親の値、initial は仕様の初期値、unset は継承するプロパティなら親の値でそれ以外は初期値、revert はブラウザの既定のスタイルに戻す。",
          "all: revert; で、すべてのプロパティをまとめて戻せる。",
        ),
      ],
    },
    // 要素の箱の大きさ・余白・枠線と、表示の方法。
    {
      id: "box",
      title: "ボックスモデル・表示",
      description: "要素の大きさ、余白、枠線、表示の方法。",
      items: [
        item(
          "box-sizing",
          "幅に枠線と余白を含める",
          "*,\n*::before,\n*::after {\n  box-sizing: border-box;\n}",
          "width と height に、padding と border を含めて計算する。",
          "既定の content-box では、指定した幅に padding と border が足されて、思ったより大きくなる。",
          "info",
        ),
        item(
          "margin-padding",
          "余白の指定",
          "/* 上下 左右 */\nmargin: 8px 16px;\n/* 上 右 下 左 */\npadding: 4px 8px 12px 16px;",
          "値の数で、上下左右への割り当てが変わる。4つなら上から時計回り。",
          "margin は枠線の外側、padding は枠線の内側の余白。",
        ),
        item(
          "logical-properties",
          "論理プロパティ",
          "margin-inline: auto;\npadding-block: 1rem;",
          "inline は文字が進む方向（横書きなら左右）、block は行が並ぶ方向（上下）を指す。",
          "縦書きや右から左に書く言語でも、そのまま正しい向きになる。margin-inline: auto で、幅を決めたブロックを横の中央に置ける。",
          "normal",
          ["inline", "block", "中央寄せ"],
        ),
        item(
          "margin-collapse",
          "マージンの相殺",
          "h2 { margin-bottom: 24px; }\np { margin-top: 16px; }\n/* 間は 40px ではなく 24px */",
          "上下に並んだブロックの margin は足されず、大きいほうだけになる。",
          "flex や grid の子では起きない。間隔を親の gap で取ると、相殺を考えなくて済む。",
        ),
        item(
          "border",
          "枠線・角丸",
          "border: 1px solid #ddd;\nborder-radius: 8px;",
          "枠線の太さ・種類・色と、角の丸みを指定する。",
          "正方形に border-radius: 50% を付けると円になる。",
        ),
        item(
          "outline",
          "outline",
          "outline: 2px solid #663399;\noutline-offset: 2px;",
          "レイアウトに影響しない線を、枠線の外側に描く。フォーカスの表示に使う。",
        ),
        item(
          "outline-none",
          "フォーカスの枠を消す",
          "button:focus {\n  outline: none;\n}",
          "フォーカスを示す枠を消す。",
          "キーボードで操作する人が、今どこにいるか分からなくなる。消すなら :focus-visible で代わりの表示を必ず用意する。",
          "warning",
        ),
        item(
          "display",
          "表示の種類",
          "display: block;\ndisplay: inline-block;\ndisplay: flex;\ndisplay: grid;",
          "要素を箱としてどう並べるかを決める。",
          "inline の要素（a、span など）には width と上下の margin が効かない。効かせるなら inline-block にする。",
        ),
        item(
          "hide",
          "隠す",
          "display: none;\nvisibility: hidden;",
          "display: none は場所ごと消し、visibility: hidden は場所を残したまま見えなくする。",
          "どちらも読み上げの対象からも外れる。",
        ),
        item(
          "visually-hidden",
          "見た目だけ隠す",
          ".visually-hidden {\n  position: absolute;\n  width: 1px;\n  height: 1px;\n  overflow: hidden;\n  clip-path: inset(50%);\n  white-space: nowrap;\n}",
          "画面には出さず、スクリーンリーダーには読ませる。",
          "アイコンだけのボタンに、読み上げ用の文字を添えるときなどに使う。",
          "info",
          ["sr-only", "スクリーンリーダー", "アクセシビリティ"],
        ),
        item(
          "overflow",
          "はみ出しの扱い",
          "overflow: auto;\noverflow: hidden;\noverflow: clip;",
          "中身が箱からはみ出したとき、スクロールさせるか、切り取って隠すかを決める。",
          "auto は必要なときだけスクロールバーを出す。clip はスクロールもできなくし、中の position: sticky を妨げない。",
        ),
        item(
          "aspect-ratio",
          "縦横比",
          "aspect-ratio: 16 / 9;",
          "幅に合わせて、高さを縦横比から決める。",
        ),
        item(
          "box-shadow",
          "影",
          "box-shadow: 0 2px 8px rgb(0 0 0 / 15%);",
          "横と縦のずれ、ぼかし、色の順で影を付ける。",
          "カンマで区切ると重ねられる。先頭に inset を付けると内側の影になる。",
        ),
      ],
    },
    // 長さの単位と計算。
    {
      id: "units",
      title: "単位・計算",
      description: "長さの単位と、値を計算する関数。",
      items: [
        item(
          "rem-em",
          "rem・em",
          "font-size: 1.125rem;\npadding: 0.5em 1em;",
          "rem はルート（html）の文字サイズ、em はその要素の文字サイズを 1 とする単位。",
          "文字サイズを rem で指定すると、ブラウザの文字サイズの設定に従う。",
          "info",
        ),
        item(
          "percent",
          "%",
          "width: 50%;",
          "親の大きさに対する割合で指定する。",
          "padding と margin の % は、上下の値も親の幅が基準になる。",
        ),
        item(
          "viewport-units",
          "画面の大きさ",
          "width: 100vw;\nheight: 100vh;",
          "vw は画面の幅、vh は画面の高さの 1%。",
          "100vw はスクロールバーの幅も含むので、縦にスクロールするページでは横にはみ出す。",
          "normal",
          ["viewport"],
        ),
        item(
          "dynamic-viewport",
          "dvh・svh・lvh",
          "min-height: 100dvh;",
          "dvh は今見えている高さ、svh はアドレスバーなどが出ているときの高さ、lvh は隠れているときの高さを基準にする。",
          "スマホでは 100vh がアドレスバーの分だけ画面より大きくなる。画面いっぱいにするなら 100dvh を使う。",
          "info",
        ),
        item(
          "text-measure",
          "文字数で幅を決める",
          "max-width: 40em;",
          "本文の1行が長くなりすぎないよう、文字の大きさを基準に幅を決める。",
          "日本語の全角文字は1文字がほぼ 1em なので、40em で1行が約40文字になる。英数字だけなら、「0」の幅を 1 とする ch が使える。",
        ),
        item(
          "calc",
          "calc()",
          "width: calc(100% - 2rem);",
          "単位の違う値どうしを計算する。",
          "+ と - の前後には空白が要る。",
        ),
        item(
          "min-max",
          "min()・max()",
          "width: min(100%, 720px);\npadding: max(1rem, 3vw);",
          "min() は候補のうち小さいほう、max() は大きいほうを使う。",
        ),
        item(
          "clamp",
          "clamp()",
          "font-size: clamp(1rem, 0.8rem + 1vw, 1.5rem);",
          "最小値と最大値の間に収めながら、画面の幅などに合わせて伸び縮みさせる。",
          "真ん中の値に rem を足しておくと、ブラウザの文字サイズの設定も効く。",
        ),
      ],
    },
    // カスタムプロパティ（CSS 変数）。
    {
      id: "custom-properties",
      title: "カスタムプロパティ（CSS 変数）",
      description: "値に名前を付けて、何度も使い回す。",
      items: [
        item(
          "define-custom-property",
          "定義する",
          ":root {\n  --color-primary: #663399;\n  --space-md: 16px;\n}",
          "-- で始まる名前で値を定義する。:root に書くとページ全体で使える。",
          "名前の大文字と小文字は区別される。",
          "normal",
          ["css variables", "変数"],
        ),
        item(
          "var",
          "使う",
          "color: var(--color-primary);\nmargin: calc(var(--space-md) * 2);",
          "var() で値を読み出す。calc() の中でも使える。",
        ),
        item(
          "var-fallback",
          "未定義のときの値",
          "padding: var(--card-padding, 1rem);",
          "変数が定義されていないとき、2つ目の値を使う。",
        ),
        item(
          "override-custom-property",
          "範囲ごとに上書き",
          ".theme-dark {\n  --color-bg: #111;\n  --color-text: #eee;\n}",
          "変数は子へ継承されるので、ある要素で値を変えると、その中だけ見た目が変わる。",
          "テーマの切り替えや、部品の種類ごとの色の違いに使う。",
        ),
        item(
          "at-property",
          "@property",
          '@property --angle {\n  syntax: "<angle>";\n  inherits: false;\n  initial-value: 0deg;\n}',
          "変数の型と初期値を登録する。型が分かるので、トランジションやアニメーションで値がなめらかに変わる。",
          "すべての主要ブラウザが対応。",
        ),
        item(
          "set-from-js",
          "JavaScript から変える",
          'element.style.setProperty("--progress", "40%");',
          "JavaScript から変数の値を書き換える。",
          '読むときは getComputedStyle(element).getPropertyValue("--progress")。',
        ),
      ],
    },
    // Flexbox。1方向に並べるレイアウト。
    {
      id: "flexbox",
      title: "Flexbox",
      description: "子要素を1方向（横か縦）に並べ、間隔や揃え方を決める。",
      items: [
        item(
          "flex",
          "横に並べる",
          ".row {\n  display: flex;\n  gap: 16px;\n}",
          "子要素を横に並べ、gap で間隔を空ける。",
          undefined,
          "normal",
          ["flex"],
        ),
        item(
          "flex-direction",
          "並べる向き",
          "flex-direction: column;",
          "column で縦に並べる。既定は row（横）。",
          "row-reverse などで逆順にすると、Tab キーや読み上げの順番と見た目がずれる。",
        ),
        item(
          "justify-content",
          "並べる方向の揃え方",
          "justify-content: space-between;",
          "並べる方向（row なら横）の位置と、余った空間の配り方を決める。",
          "flex-start、center、flex-end、space-between、space-around、space-evenly から選ぶ。",
        ),
        item(
          "align-items",
          "直角の方向の揃え方",
          "align-items: center;",
          "並べる方向と直角の向き（row なら縦）の揃え方を決める。",
          "既定の stretch では、子の高さがそろう。文字の下端でそろえるなら baseline。",
        ),
        item(
          "flex-center",
          "上下左右の中央に置く",
          ".center {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}",
          "子要素を箱の真ん中に置く。",
          "grid なら display: grid; place-items: center; の2行で書ける。",
          "normal",
          ["中央寄せ", "センタリング"],
        ),
        item(
          "flex-wrap",
          "折り返す",
          "flex-wrap: wrap;",
          "1行に入りきらない子を、次の行へ折り返す。",
        ),
        item(
          "flex-grow",
          "残りの幅を埋める",
          ".main { flex: 1; }",
          "余った幅を、flex の値の比で分けて広げる。",
          "flex: 1 は flex: 1 1 0% の省略形。",
        ),
        item(
          "flex-shrink",
          "縮ませない",
          ".icon { flex-shrink: 0; }",
          "幅が足りないときでも、その子を縮めない。",
        ),
        item(
          "flex-min-width",
          "中身がはみ出すのを防ぐ",
          ".content { min-width: 0; }",
          "長い文字列やコードを含む子が縮まずにはみ出すのを防ぐ。",
          "flex の子の min-width は既定で auto（中身の幅）なので、中身より狭くならない。grid の子も同じ。",
          "info",
        ),
        item(
          "margin-auto",
          "一部だけ反対の端に寄せる",
          ".nav .login { margin-left: auto; }",
          "auto の margin が余白を吸収し、その子から後ろを反対の端に寄せる。",
        ),
        item(
          "order",
          "表示の順番を変える",
          ".sidebar { order: -1; }",
          "子の表示の順番を変える。小さい値ほど前に並ぶ。",
          "変わるのは見た目だけで、Tab キーや読み上げの順番は HTML のまま。順番に意味がある内容には使わない。",
          "warning",
        ),
      ],
    },
    // Grid。行と列の2方向のレイアウト。
    {
      id: "grid",
      title: "Grid",
      description: "行と列の2方向で、要素を格子状に配置する。",
      items: [
        item(
          "grid-columns",
          "列を作る",
          ".grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 16px;\n}",
          "同じ幅の3列に並べる。fr は余った幅を分け合う単位。",
          undefined,
          "normal",
          ["grid"],
        ),
        item(
          "grid-auto-fit",
          "幅に合わせて列の数を変える",
          "grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));",
          "1列 240px 以上を保てる数だけ列を作る。メディアクエリなしで画面の幅に合わせられる。",
          "auto-fill にすると、子が足りないときも空の列を残す。",
          "info",
          ["レスポンシブ"],
        ),
        item(
          "grid-fixed-fluid",
          "列ごとに幅を決める",
          "grid-template-columns: 240px minmax(0, 1fr);",
          "固定幅のサイドバーと、残りの本文のように、列ごとに幅を指定する。",
          "1fr だけだと、長い中身で列が広がって崩れる。minmax(0, 1fr) にすると収まる。",
        ),
        item(
          "grid-span",
          "複数の列にまたがる",
          ".wide { grid-column: span 2; }",
          "2列分の幅を使う。",
        ),
        item(
          "grid-line",
          "線の番号で置く",
          ".header { grid-column: 1 / -1; }",
          "始まりと終わりの線の番号で置く。-1 は最後の線なので、1 / -1 で全部の列にまたがる。",
        ),
        item(
          "grid-areas",
          "名前を付けて配置",
          '.layout {\n  display: grid;\n  grid-template-columns: 200px 1fr;\n  grid-template-areas:\n    "header header"\n    "side   main";\n}\n.header { grid-area: header; }',
          "領域に名前を付け、見た目どおりに並べて配置を書く。",
        ),
        item(
          "place-items",
          "中央に置く",
          ".center {\n  display: grid;\n  place-items: center;\n}",
          "子要素を、それぞれの場所の上下左右の中央に置く。",
          undefined,
          "normal",
          ["中央寄せ", "センタリング"],
        ),
        item(
          "subgrid",
          "親のグリッドにそろえる",
          ".card {\n  display: grid;\n  grid-row: span 3;\n  grid-template-rows: subgrid;\n}",
          "子のグリッドで、親の行（や列）の線をそのまま使う。横に並んだカードの見出しや本文の高さがそろう。",
          "すべての主要ブラウザが対応。",
        ),
        item(
          "grid-dense",
          "隙間を詰める",
          "grid-auto-flow: dense;",
          "空いた場所に、後ろにある小さい子を詰めて置く。",
          "見た目の順番が HTML の順番とずれ、Tab キーや読み上げの順番と食い違う。",
          "warning",
        ),
      ],
    },
    // 通常の並びから外して置く方法と、重なりの順番。
    {
      id: "position",
      title: "配置・重なり",
      description: "要素を通常の並びから外して置く方法と、重なりの順番。",
      items: [
        item(
          "position-relative",
          "relative",
          ".wrapper { position: relative; }",
          "元の位置を基準に、少しずらして置ける。中の absolute の要素の基準にもなる。",
        ),
        item(
          "position-absolute",
          "absolute",
          ".badge {\n  position: absolute;\n  top: 8px;\n  right: 8px;\n}",
          "position が static 以外の、いちばん近い祖先を基準に置く。",
          "通常の並びから外れ、周りの要素はその場所が空いているものとして並ぶ。",
        ),
        item(
          "position-fixed",
          "画面に固定",
          ".to-top {\n  position: fixed;\n  right: 16px;\n  bottom: 16px;\n}",
          "スクロールしても、画面の同じ位置に留める。",
          "祖先に transform や filter があると、その祖先が基準になって画面に固定されない。",
        ),
        item(
          "position-sticky",
          "スクロールで貼り付く",
          ".toc {\n  position: sticky;\n  top: 0;\n}",
          "スクロールして top の位置まで来ると、親の範囲の中で貼り付く。",
          "top などの位置を指定しないと効かない。祖先に overflow: hidden や auto があると、その中でしか貼り付かない。",
        ),
        item(
          "inset",
          "上下左右をまとめて",
          ".overlay {\n  position: absolute;\n  inset: 0;\n}",
          "top・right・bottom・left をまとめて指定する。inset: 0 で基準の箱いっぱいに広がる。",
        ),
        item(
          "z-index",
          "重なりの順番",
          ".modal {\n  position: relative;\n  z-index: 10;\n}",
          "値が大きいほど手前に表示する。",
          "位置指定した要素と、flex・grid の子にだけ効く。親が別の重なりのグループ（スタッキングコンテキスト）を作っていると、親の外にある要素より手前には出られない。",
          "normal",
          ["stacking context", "スタッキングコンテキスト"],
        ),
        item(
          "isolation",
          "重なりのグループを作る",
          ".card { isolation: isolate; }",
          "新しいスタッキングコンテキストを作り、中の z-index の影響をその中に閉じ込める。",
        ),
        item(
          "anchor-positioning",
          "ほかの要素に合わせて置く",
          ".menu-button {\n  anchor-name: --menu;\n}\n.menu {\n  position: absolute;\n  position-anchor: --menu;\n  position-area: bottom;\n  position-try-fallbacks: flip-block;\n}",
          "別の要素（アンカー）を基準に、メニューやツールチップを置く。下に入りきらないときは上に回す。",
          "アンカー配置。Chrome・Edge 129、Firefox 147、Safari 26 から使える。",
          "normal",
          ["anchor", "アンカー", "tooltip"],
        ),
        item(
          "float",
          "文章を回り込ませる",
          "img.left {\n  float: left;\n  margin-right: 1rem;\n}",
          "画像の横に文章を回り込ませる。",
          "段組みのレイアウトには flex や grid を使う。",
        ),
      ],
    },
    // フォント、文字の大きさと行の高さ、折り返しと省略。
    {
      id: "text",
      title: "文字・フォント",
      description: "フォント、文字の大きさと行の高さ、折り返しと省略。",
      items: [
        item(
          "font-family",
          "フォントの指定",
          'font-family: "Noto Sans JP", system-ui, sans-serif;',
          "左から順に、使えるフォントを探して使う。",
          "最後に sans-serif や serif などの総称を書いておく。",
        ),
        item(
          "font-face",
          "Web フォントを読み込む",
          '@font-face {\n  font-family: "MyFont";\n  src: url("/fonts/myfont.woff2") format("woff2");\n  font-display: swap;\n}',
          "フォントのファイルを読み込み、名前を付ける。",
          "font-display: swap で、読み込み中は別のフォントで先に文字を表示する。",
        ),
        item(
          "font-size-weight",
          "大きさ・太さ",
          "font-size: 1rem;\nfont-weight: 700;",
          "文字の大きさと太さを指定する。太さは 100〜900 で、400 が標準、700 が太字。",
        ),
        item(
          "line-height",
          "行の高さ",
          "line-height: 1.7;",
          "行の高さを指定する。単位の無い数値は、文字サイズの何倍かを表す。",
          "単位を付けないと、子要素でもその文字サイズに対する倍率として引き継がれる。",
          "info",
        ),
        item(
          "letter-spacing",
          "字間",
          "letter-spacing: 0.05em;",
          "文字の間隔を広げる。マイナスの値で詰める。",
        ),
        item(
          "palt",
          "日本語の字詰め",
          'font-feature-settings: "palt";',
          "約物（、。「」など）や仮名の幅を詰めて組む。",
          "フォントが詰め組みの情報を持っているときだけ効く。見出しなど短い文字に向く。",
        ),
        item(
          "text-ellipsis",
          "1行で省略（…）",
          ".title {\n  overflow: hidden;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n}",
          "はみ出した文字を … で省略する。",
          "3つのプロパティをそろえて指定する。",
          "normal",
          ["三点リーダー", "truncate"],
        ),
        item(
          "line-clamp",
          "複数行で省略",
          ".excerpt {\n  display: -webkit-box;\n  -webkit-box-orient: vertical;\n  -webkit-line-clamp: 3;\n  overflow: hidden;\n}",
          "3行を超えた部分を … で省略する。",
          "-webkit- の付いた書き方だが、すべての主要ブラウザで使える。",
        ),
        item(
          "overflow-wrap",
          "長い単語や URL を折り返す",
          "overflow-wrap: anywhere;",
          "枠に収まらない長い英単語や URL を、途中で折り返す。",
          "break-word でも折り返すが、要素の最小幅の計算には入らないので、flex の子などでは縮まずにはみ出すことがある。",
        ),
        item(
          "word-break-auto-phrase",
          "日本語を文節で折り返す",
          "word-break: auto-phrase;",
          "日本語の文章を、単語の途中ではなく文節の区切りで折り返す。",
          "今は Chrome と Edge だけが対応。ほかのブラウザでは通常の折り返しになる。",
        ),
        item(
          "text-wrap-balance",
          "見出しの行の長さをそろえる",
          "h1 { text-wrap: balance; }",
          "複数行になった見出しの、各行の長さをそろえる。",
          "すべての主要ブラウザが対応。数行の見出し向けで、長い段落には効かない。",
        ),
        item(
          "text-wrap-pretty",
          "最後の行が短くなるのを防ぐ",
          "p { text-wrap: pretty; }",
          "段落の最後の行に1語だけが残らないよう、折り返しの位置を調整する。",
          "Chrome・Edge・Safari が対応。Firefox では通常の折り返しになる。",
        ),
        item(
          "white-space",
          "改行と空白をそのまま表示",
          "white-space: pre-wrap;",
          "HTML の中の改行と空白をそのまま表示し、端では折り返す。",
        ),
        item(
          "text-underline",
          "下線",
          "text-decoration: underline;\ntext-underline-offset: 0.2em;",
          "下線を引き、文字との間隔を調整する。",
        ),
        item(
          "writing-mode",
          "縦書き",
          "writing-mode: vertical-rl;",
          "縦書きにする。行は右から左へ並ぶ。",
          "縦書きの中の2桁の数字を横に並べるなら text-combine-upright: all。",
        ),
      ],
    },
    // 色の書き方と背景。ライト／ダークの切り替え。
    {
      id: "color",
      title: "色・背景",
      description: "色の書き方、背景とグラデーション、ライト／ダークの切り替え。",
      items: [
        item(
          "color-formats",
          "色の書き方",
          "color: #663399;\ncolor: rgb(102 51 153 / 80%);\ncolor: hsl(270 50% 40%);",
          "16進数、rgb()、hsl() で色を書く。/ の後ろは不透明度。",
          "rgb(102, 51, 153) のようにカンマで区切る書き方も使える。",
        ),
        item(
          "oklch",
          "oklch()",
          "color: oklch(55% 0.15 300);",
          "明るさ・鮮やかさ・色相で色を書く。明るさの数値が見た目の明るさと合うので、色の段階を作りやすい。",
          "すべての主要ブラウザが対応。",
        ),
        item(
          "currentcolor",
          "currentColor",
          "border: 1px solid currentColor;\nfill: currentColor;",
          "その要素の color の値を使う。",
          "SVG のアイコンを文字の色に合わせるときに使う。",
        ),
        item(
          "color-mix",
          "色を混ぜる",
          "background: color-mix(in oklch, var(--brand) 20%, white);",
          "2つの色を、指定した割合で混ぜる。",
          "transparent と混ぜると、半透明の色を作れる。",
        ),
        item(
          "relative-color",
          "元の色から作る",
          "background: oklch(from var(--brand) calc(l + 0.2) c h);",
          "元の色を成分に分け、明るさなどを変えた色を作る。",
          "すべての主要ブラウザが対応。",
        ),
        item(
          "color-scheme",
          "ライト／ダークに対応する",
          ":root { color-scheme: light dark; }",
          "ページがライトとダークの両方に対応することを伝える。フォーム部品やスクロールバーの色も切り替わる。",
          undefined,
          "info",
          ["ダークモード", "dark mode"],
        ),
        item(
          "light-dark",
          "light-dark()",
          "color: light-dark(#333, #eee);",
          "ライトのときの色とダークのときの色を、1つの値で書く。",
          "color-scheme の指定が必要。すべての主要ブラウザが対応。",
          "normal",
          ["ダークモード", "dark mode"],
        ),
        item(
          "background",
          "背景画像",
          'background: url("hero.jpg") center / cover no-repeat;',
          "背景の画像・位置・大きさ・繰り返しをまとめて指定する。",
          "cover は隙間なく覆い、contain は全体が収まるように縮める。",
        ),
        item(
          "gradient",
          "グラデーション",
          "background: linear-gradient(135deg, #663399, #d63384);",
          "角度と色を指定して、直線方向のグラデーションを描く。",
          "円形は radial-gradient()、扇形は conic-gradient()。",
        ),
        item(
          "opacity",
          "透明度",
          "opacity: 0.6;",
          "要素全体を、中身も含めて半透明にする。",
          "背景だけを透かすなら、rgb(0 0 0 / 50%) のように色の側で指定する。",
        ),
        item(
          "filter",
          "ぼかしなどの効果",
          "filter: grayscale(1);\nbackdrop-filter: blur(8px);",
          "filter は要素自身に、backdrop-filter は要素の後ろに見えるものに、ぼかしなどの効果をかける。",
          "backdrop-filter もすべての主要ブラウザが対応。",
        ),
      ],
    },
    // 画面・設定・コンテナの大きさ・ブラウザの対応で切り替える。
    {
      id: "responsive",
      title: "レスポンシブ・条件付きのスタイル",
      description:
        "画面の幅や利用者の設定、置かれた場所の大きさ、ブラウザの対応に合わせてスタイルを変える。",
      items: [
        item(
          "media-width",
          "画面の幅で切り替える",
          "@media (width >= 768px) {\n  .grid { grid-template-columns: repeat(2, 1fr); }\n}",
          "画面の幅が条件に合うときだけ、中のスタイルを当てる。",
          "HTML に meta viewport が必要。>= のような範囲の書き方はすべての主要ブラウザが対応（以前の書き方は min-width: 768px）。",
          "normal",
          ["media query", "メディアクエリ", "ブレークポイント"],
        ),
        item(
          "prefers-color-scheme",
          "OS のダークモード",
          "@media (prefers-color-scheme: dark) {\n  :root { --color-bg: #111; }\n}",
          "OS やブラウザの設定がダークモードのときだけ当てる。",
          undefined,
          "normal",
          ["ダークモード", "dark mode"],
        ),
        item(
          "prefers-reduced-motion",
          "動きを減らす設定",
          "@media (prefers-reduced-motion: reduce) {\n  .hero { animation: none; }\n}",
          "動きを減らす設定にしている人には、アニメーションを止める。",
          "大きな動きで気分が悪くなる人がいる。画面全体が動く演出は、この条件で止める。",
          "info",
          ["アクセシビリティ"],
        ),
        item(
          "hover-pointer",
          "マウスのある環境",
          "@media (hover: hover) and (pointer: fine) {\n  .card:hover { translate: 0 -2px; }\n}",
          "マウスなど、ホバーできて細かく指せる入力があるときだけ当てる。",
        ),
        item(
          "container-query",
          "コンテナクエリ",
          ".cards { container-type: inline-size; }\n\n@container (width >= 480px) {\n  .card { display: flex; }\n}",
          "画面ではなく、親（コンテナ）の幅に合わせてスタイルを変える。",
          "同じ部品を、広い場所にも狭い場所にも置くときに向く。すべての主要ブラウザが対応。",
          "info",
          ["container queries", "@container"],
        ),
        item(
          "container-units",
          "コンテナの幅の単位",
          ".card h2 { font-size: clamp(1rem, 5cqi, 2rem); }",
          "cqi は、いちばん近いコンテナの横幅の 1%。",
        ),
        item(
          "style-query",
          "スタイルクエリ",
          ".card-list { --layout: compact; }\n\n@container style(--layout: compact) {\n  .card { padding: 8px; }\n}",
          "親のカスタムプロパティの値で、スタイルを切り替える。",
          "すべての主要ブラウザが対応（2026年5月から）。調べられるのはカスタムプロパティだけ。container-type の指定は要らない。",
        ),
        item(
          "responsive-image",
          "画像を幅に収める",
          "img {\n  max-width: 100%;\n  height: auto;\n}",
          "画像が親の幅より大きくならないようにする。",
        ),
        item(
          "object-fit",
          "画像を枠に合わせて切り抜く",
          "img {\n  width: 100%;\n  aspect-ratio: 4 / 3;\n  object-fit: cover;\n}",
          "縦横比を保ったまま枠を覆い、はみ出した部分を切り取る。",
          "contain にすると全体が収まるように縮める。切り取る位置は object-position で決める。",
        ),
        item(
          "supports",
          "@supports",
          "@supports (display: grid) { … }\n@supports not (anchor-name: --a) { … }",
          "ブラウザがその書き方に対応しているときだけ当てる。not で、対応していないときの代わりを書ける。",
        ),
        item(
          "supports-selector",
          "セレクターの対応を調べる",
          "@supports selector(:has(a)) { … }",
          "そのセレクターに対応しているかで書き分ける。",
        ),
      ],
    },
    // トランジションとアニメーション。新しい表示・画面の切り替えの動きもここ。
    {
      id: "animation",
      title: "トランジション・アニメーション",
      description: "値の変化をなめらかにするトランジションと、キーフレームで動かすアニメーション。",
      items: [
        item(
          "transition",
          "トランジション",
          ".button {\n  transition: background-color 0.2s ease;\n}\n.button:hover {\n  background-color: #552288;\n}",
          "値が変わるときに、指定した時間をかけてなめらかに変える。",
          "transition: all は思わぬプロパティまで動くので、対象を並べて書く。",
        ),
        item(
          "transform",
          "移動・拡大・回転",
          "transform: translateY(-4px) scale(1.05) rotate(3deg);",
          "レイアウトを変えずに、見た目だけを動かす。",
          "位置を動かすなら top や left より transform のほうが描画の負荷が軽い。",
          "info",
        ),
        item(
          "individual-transform",
          "変形を1つずつ指定",
          "translate: 0 -4px;\nscale: 1.05;\nrotate: 3deg;",
          "移動・拡大・回転を別々のプロパティで指定する。1つだけ上書きしやすい。",
        ),
        item(
          "keyframes",
          "キーフレーム",
          "@keyframes fade-in {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}",
          "アニメーションの途中の状態を定義する。0%〜100% で細かく区切れる。",
        ),
        item(
          "animation",
          "アニメーションを付ける",
          ".toast { animation: fade-in 0.3s ease-out both; }",
          "キーフレームの名前・時間・速度の変化などをまとめて指定する。",
          "infinite で繰り返し、alternate で往復する。both で、始まる前と終わった後も最初と最後の状態を保つ。",
        ),
        item(
          "starting-style",
          "表示されたときに動かす",
          ".panel {\n  opacity: 1;\n  transition: opacity 0.3s;\n}\n@starting-style {\n  .panel { opacity: 0; }\n}",
          "要素が表示された直後の、変化前の値を指定する。追加した要素や display: none から表示した要素にも、トランジションが効く。",
          "すべての主要ブラウザが対応。",
        ),
        item(
          "allow-discrete",
          "消えるときも動かす",
          ".panel {\n  transition: opacity 0.3s, display 0.3s allow-discrete;\n}\n.panel.is-hidden {\n  display: none;\n  opacity: 0;\n}",
          "display を切り替える時点をトランジションの最後にずらし、消えるときのアニメーションを見せる。",
          "display の切り替えに効くのは Chrome・Edge・Safari。Firefox では、すぐに消える。",
        ),
        item(
          "view-transition",
          "画面の切り替えアニメーション",
          "document.startViewTransition(() => {\n  updateDOM();\n});",
          "DOM を書き換える前と後の画面を、クロスフェードなどでつなぐ。",
          "すべての主要ブラウザが対応（2025年10月から）。動きは ::view-transition-old(root) と ::view-transition-new(root) で変えられる。",
          "normal",
          ["view transitions"],
        ),
        item(
          "view-transition-name",
          "要素ごとにつなぐ",
          ".thumbnail { view-transition-name: hero; }",
          "切り替えの前後で同じ名前の要素を、位置と大きさがつながるように動かす。",
          "同じ名前は、1つの画面に1つだけ付ける。",
        ),
        item(
          "cross-document-view-transition",
          "ページの移動をつなぐ",
          "@view-transition {\n  navigation: auto;\n}",
          "同じオリジンの別のページへ移るときも、切り替えのアニメーションを付ける。",
          "移る前と後のページの両方に書く。Chrome・Edge・Safari が対応。Firefox では通常の移動になる。",
        ),
        item(
          "scroll-driven",
          "スクロールに合わせて動かす",
          ".progress {\n  animation: grow linear;\n  animation-timeline: scroll();\n}",
          "時間ではなく、スクロールした量に合わせてアニメーションを進める。",
          "Chrome・Edge と Safari 26 が対応。Firefox ではまだ使えない。",
        ),
        item(
          "interpolate-size",
          "auto の高さまで動かす",
          ":root { interpolate-size: allow-keywords; }",
          "height: auto のようなキーワードの値へも、トランジションで変化させられるようにする。",
          "今は Chrome と Edge だけが対応。ほかのブラウザでは、動かずにすぐ切り替わる。",
        ),
        item(
          "will-change",
          "will-change",
          ".slider { will-change: transform; }",
          "これから変わるプロパティをブラウザに伝え、先に準備させる。",
          "メモリを多く使うので、実際に動きがカクつく要素だけに付ける。",
          "warning",
        ),
      ],
    },
    // スクロールの動きと、フォーム部品・ダイアログの見た目。
    {
      id: "ui",
      title: "スクロール・フォーム部品",
      description: "スクロールの動き、フォーム部品、ダイアログとポップオーバーの見た目。",
      items: [
        item(
          "scroll-behavior",
          "なめらかにスクロール",
          "@media (prefers-reduced-motion: no-preference) {\n  html { scroll-behavior: smooth; }\n}",
          "ページ内リンクなどで、なめらかにスクロールする。",
          "動きを減らす設定の人には効かないよう、メディアクエリで囲む。",
        ),
        item(
          "scroll-margin",
          "固定ヘッダーの分ずらす",
          "h2 { scroll-margin-top: 80px; }",
          "ページ内リンクで移ったとき、固定ヘッダーに隠れないよう上に余白を取る。",
        ),
        item(
          "scroll-snap",
          "スクロールで吸着",
          ".slider {\n  display: flex;\n  overflow-x: auto;\n  scroll-snap-type: x mandatory;\n}\n.slide { scroll-snap-align: start; }",
          "スクロールが止まったとき、子要素の端にぴったり合わせる。",
          "mandatory は必ず合わせ、proximity は近いときだけ合わせる。",
        ),
        item(
          "overscroll-behavior",
          "スクロールの連鎖を止める",
          ".modal-body { overscroll-behavior: contain; }",
          "中のスクロールが端まで行っても、後ろのページまでスクロールさせない。",
        ),
        item(
          "scrollbar-gutter",
          "スクロールバーの場所を空けておく",
          "html { scrollbar-gutter: stable; }",
          "スクロールバーが出たり消えたりしても、レイアウトが横にずれないようにする。",
          "すべての主要ブラウザが対応。",
        ),
        item(
          "accent-color",
          "フォーム部品の色",
          ":root { accent-color: #663399; }",
          "チェックボックス、ラジオボタン、スライダーなどの色をまとめて変える。",
          "Safari は 26.2 から対応。",
        ),
        item(
          "appearance",
          "標準の見た目を消す",
          "select { appearance: none; }",
          "フォーム部品の、ブラウザ標準の見た目を消して自分で作る。",
        ),
        item(
          "field-sizing",
          "中身に合わせて伸ばす",
          "textarea { field-sizing: content; }",
          "入力した文字の量に合わせて、テキストエリアや入力欄の大きさを変える。",
          "すべての主要ブラウザが対応（2026年6月から）。min-height や max-height と一緒に使う。",
        ),
        item(
          "resize",
          "大きさの変更を縦だけにする",
          "textarea { resize: vertical; }",
          "テキストエリアの大きさを、利用者が縦方向だけ変えられるようにする。",
        ),
        item(
          "pointer-events",
          "クリックを後ろへ通す",
          ".overlay { pointer-events: none; }",
          "その要素がクリックなどを受け取らず、後ろの要素に通す。",
          "キーボードでのフォーカスや操作は止まらない。",
        ),
        item(
          "user-select",
          "文字を選択できなくする",
          ".handle { user-select: none; }",
          "文字を選択できないようにする。",
          "コピーしたい人の妨げになるので、ドラッグして使う部品などに限る。",
        ),
        item(
          "backdrop",
          "::backdrop",
          "dialog::backdrop {\n  background: rgb(0 0 0 / 50%);\n}",
          "モーダルのダイアログや、ポップオーバーの後ろに敷く幕を指定する。",
        ),
        item(
          "open-state",
          "開いている状態",
          "dialog[open] { }\n[popover]:popover-open { }",
          "開いているダイアログとポップオーバーに一致する。",
        ),
      ],
    },
    // 思いどおりに表示されないときの確かめ方と直し方。
    {
      id: "trouble",
      title: "よくある問題",
      description: "思いどおりに表示されないときの確かめ方と直し方。",
      items: [
        item(
          "style-not-applied",
          "スタイルが当たらない",
          undefined,
          "開発者ツールで要素を選び、打ち消し線の付いた宣言と、それを上書きしているルールを確かめる。",
          "詳細度で負けている、後から別のルールが上書きしている、セレクターのつづりが違う、がよくある原因。",
        ),
        item(
          "debug-outline",
          "箱の範囲を確かめる",
          "* { outline: 1px solid rgb(255 0 0 / 40%); }",
          "すべての要素に線を引き、どこがはみ出しているかを見る。",
          "outline はレイアウトに影響しない。確かめ終わったら消す。",
        ),
        item(
          "horizontal-overflow",
          "横スクロールが出る",
          '[...document.querySelectorAll("*")].filter(\n  (el) => el.getBoundingClientRect().right > innerWidth,\n);',
          "画面の右端をはみ出している要素を、開発者ツールのコンソールで探す。",
          "100vw、長い URL、固定幅の画像や表がよくある原因。",
        ),
        item(
          "z-index-not-working",
          "z-index が効かない",
          ".item {\n  position: relative;\n  z-index: 1;\n}",
          "まず position を指定する（flex・grid の子なら要らない）。",
          "それでも手前に出ないときは、祖先の opacity・transform・filter・z-index が別のスタッキングコンテキストを作っていないかを確かめる。",
        ),
        item(
          "sticky-not-working",
          "sticky が効かない",
          ".header {\n  position: sticky;\n  top: 0;\n}",
          "top などの位置を指定し、祖先に overflow: hidden や auto が無いかを確かめる。",
          "親の高さが中身と同じだと、動ける余地がなく貼り付かない。",
        ),
        item(
          "image-gap",
          "画像の下に隙間ができる",
          "img { display: block; }",
          "画像は文字と同じく行の中に置かれ、下に文字のはみ出し分の隙間ができる。block にすると消える。",
          "vertical-align: middle でも消える。",
        ),
        item(
          "percent-height",
          "height: 100% が効かない",
          ".hero { min-height: 100dvh; }",
          "% の高さは、親の高さが決まっていないと効かない。画面の高さに合わせるなら dvh を使う。",
        ),
        item(
          "inline-block-gap",
          "横に並べた要素の間に隙間ができる",
          ".list {\n  display: flex;\n  gap: 8px;\n}",
          "inline-block で並べると、HTML の改行が空白として表示される。親を flex にすると消え、間隔は gap で決められる。",
        ),
        item(
          "ios-input-zoom",
          "iPhone で入力欄が拡大される",
          "input,\nselect,\ntextarea {\n  font-size: 16px;\n}",
          "iOS の Safari は、文字サイズが 16px 未満の入力欄を押すと画面を拡大する。16px 以上にする。",
        ),
      ],
    },
  ],
};
